"""Physics Projector — PhysDiff-inspired physics projection for 2D skeletal animation.

Inspired by PhysDiff (ICCV 2023), this module implements a lightweight 2D physics
engine based on Verlet integration and Position-Based Dynamics (PBD). It acts as a
post-processing layer that "projects" raw animation poses into a physically plausible
subspace, eliminating artifacts like foot sliding, ground penetration, and unnatural
stiffness.

**Critical design decision**: The existing renderer (`render_character_frame`) works
with angle-based pose dicts (`dict[str, float]`). This module therefore provides TWO
integration paths:

1. **AnglePoseProjector** (recommended): Works directly in angle space. It applies
   spring-damper physics to joint angles, producing smooth, physically-motivated
   secondary motion without breaking the renderer contract.

2. **PositionPhysicsProjector**: Works in position space using full Verlet integration
   and PBD. Converts corrected positions back to angles via inverse kinematics.
   More physically accurate but heavier.

Architecture overview (PhysDiff → 2D migration):
  1. Raw pose generated by existing animation system (presets.py, IK, etc.)
  2. Projector receives the raw pose and applies physics corrections
  3. Corrected pose returned as dict[str, float] for rendering

Mathematical foundations:
  - Verlet Integration: x(t+dt) = x(t) + (x(t) - x(t-dt)) + a(t)*dt²
  - PBD Distance Constraint: Δx = (|x2-x1| - L₀) / |x2-x1| * (x2-x1) * 0.5
  - Spring-Damper: F = -k*(θ - θ_target) - c*ω (angular spring)
  - Ground Constraint: if foot_y < ground_y then correct leg angles
  - Cognitive Motion: anticipation, follow-through, overlapping action

References:
  - PhysDiff: https://arxiv.org/abs/2212.02500
  - Jakobsen, "Advanced Character Physics" (GDC 2001)
  - Pikuma, "Verlet Integration and Cloth Physics Simulation"

Usage::

    from mathart.animation.physics_projector import AnglePoseProjector

    projector = AnglePoseProjector()

    # In the animation loop:
    raw_pose = idle_animation(t)
    corrected_pose = projector.step(raw_pose, dt=1/60)
    # corrected_pose is a dict[str, float] — same contract as raw_pose
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Optional, Callable

import numpy as np


# ── Angular Spring-Damper State ───────────────────────────────────────────────


@dataclass
class AngularSpringState:
    """State of an angular spring-damper for a single joint.

    Uses the equation of motion:
        I * α = -k * (θ - θ_target) - c * ω + τ_ext

    where:
        I = moment of inertia
        k = angular spring stiffness
        c = angular damping coefficient
        θ = current angle
        ω = angular velocity (dθ/dt)
        θ_target = target angle from animation
        τ_ext = external torque (gravity, etc.)
    """
    angle: float = 0.0
    angular_velocity: float = 0.0
    prev_target: float = 0.0


@dataclass
class JointPhysicsConfig:
    """Physics configuration for a single joint.

    Parameters
    ----------
    spring_k : float
        Angular spring stiffness. Higher = snappier tracking.
        Range: 50-500 for primary joints, 10-50 for secondary.
    damping_c : float
        Angular damping. Higher = less oscillation.
        Range: 5-30.
    inertia : float
        Moment of inertia. Higher = more sluggish response.
        Range: 0.5-5.0.
    is_primary : bool
        If True, this joint closely follows the animation target.
        If False, it has more freedom to exhibit secondary motion.
    gravity_sensitivity : float
        How much this joint is affected by gravity torque.
        Range: 0.0-1.0. Arms/head should be higher.
    follow_through_strength : float
        Strength of follow-through effect (continuation after stop).
        Range: 0.0-1.0.
    anticipation_strength : float
        Strength of anticipation (brief reverse before main motion).
        Range: 0.0-0.3.
    overlap_delay : float
        Delay in seconds for overlapping action.
        Range: 0.0-0.1.
    """
    spring_k: float = 200.0
    damping_c: float = 15.0
    inertia: float = 1.0
    is_primary: bool = True
    gravity_sensitivity: float = 0.0
    follow_through_strength: float = 0.0
    anticipation_strength: float = 0.0
    overlap_delay: float = 0.0


# ── Default Joint Physics Profiles ────────────────────────────────────────────

# These profiles encode the "personality" of each joint's physics behavior.
# Primary joints (spine, hips, knees) track the animation tightly.
# Secondary joints (head, hands, elbows) have more freedom for natural motion.

DEFAULT_JOINT_PHYSICS: dict[str, JointPhysicsConfig] = {
    # Spine chain: tight tracking, minimal secondary motion
    "hip": JointPhysicsConfig(
        spring_k=350.0, damping_c=22.0, inertia=2.5,
        is_primary=True, gravity_sensitivity=0.0,
        follow_through_strength=0.05, anticipation_strength=0.03,
    ),
    "spine": JointPhysicsConfig(
        spring_k=300.0, damping_c=20.0, inertia=2.0,
        is_primary=True, gravity_sensitivity=0.0,
        follow_through_strength=0.1, anticipation_strength=0.05,
    ),
    "chest": JointPhysicsConfig(
        spring_k=280.0, damping_c=18.0, inertia=1.8,
        is_primary=True, gravity_sensitivity=0.0,
        follow_through_strength=0.15, anticipation_strength=0.05,
    ),
    "neck": JointPhysicsConfig(
        spring_k=150.0, damping_c=12.0, inertia=0.8,
        is_primary=False, gravity_sensitivity=0.1,
        follow_through_strength=0.3, anticipation_strength=0.1,
    ),
    "head": JointPhysicsConfig(
        spring_k=120.0, damping_c=10.0, inertia=1.2,
        is_primary=False, gravity_sensitivity=0.15,
        follow_through_strength=0.4, anticipation_strength=0.1,
        overlap_delay=0.03,
    ),

    # Arms: moderate tracking, good secondary motion
    "l_shoulder": JointPhysicsConfig(
        spring_k=180.0, damping_c=14.0, inertia=1.0,
        is_primary=False, gravity_sensitivity=0.2,
        follow_through_strength=0.35, anticipation_strength=0.08,
        overlap_delay=0.02,
    ),
    "r_shoulder": JointPhysicsConfig(
        spring_k=180.0, damping_c=14.0, inertia=1.0,
        is_primary=False, gravity_sensitivity=0.2,
        follow_through_strength=0.35, anticipation_strength=0.08,
        overlap_delay=0.02,
    ),
    "l_elbow": JointPhysicsConfig(
        spring_k=100.0, damping_c=8.0, inertia=0.6,
        is_primary=False, gravity_sensitivity=0.3,
        follow_through_strength=0.5, anticipation_strength=0.0,
        overlap_delay=0.04,
    ),
    "r_elbow": JointPhysicsConfig(
        spring_k=100.0, damping_c=8.0, inertia=0.6,
        is_primary=False, gravity_sensitivity=0.3,
        follow_through_strength=0.5, anticipation_strength=0.0,
        overlap_delay=0.04,
    ),
    "l_hand": JointPhysicsConfig(
        spring_k=60.0, damping_c=5.0, inertia=0.3,
        is_primary=False, gravity_sensitivity=0.4,
        follow_through_strength=0.6, anticipation_strength=0.0,
        overlap_delay=0.06,
    ),
    "r_hand": JointPhysicsConfig(
        spring_k=60.0, damping_c=5.0, inertia=0.3,
        is_primary=False, gravity_sensitivity=0.4,
        follow_through_strength=0.6, anticipation_strength=0.0,
        overlap_delay=0.06,
    ),

    # Legs: tight tracking (critical for locomotion)
    "l_hip": JointPhysicsConfig(
        spring_k=350.0, damping_c=22.0, inertia=1.5,
        is_primary=True, gravity_sensitivity=0.0,
        follow_through_strength=0.1, anticipation_strength=0.05,
    ),
    "r_hip": JointPhysicsConfig(
        spring_k=350.0, damping_c=22.0, inertia=1.5,
        is_primary=True, gravity_sensitivity=0.0,
        follow_through_strength=0.1, anticipation_strength=0.05,
    ),
    "l_knee": JointPhysicsConfig(
        spring_k=320.0, damping_c=20.0, inertia=1.2,
        is_primary=True, gravity_sensitivity=0.0,
        follow_through_strength=0.15, anticipation_strength=0.0,
    ),
    "r_knee": JointPhysicsConfig(
        spring_k=320.0, damping_c=20.0, inertia=1.2,
        is_primary=True, gravity_sensitivity=0.0,
        follow_through_strength=0.15, anticipation_strength=0.0,
    ),
    "l_foot": JointPhysicsConfig(
        spring_k=250.0, damping_c=18.0, inertia=0.8,
        is_primary=True, gravity_sensitivity=0.0,
        follow_through_strength=0.2, anticipation_strength=0.0,
    ),
    "r_foot": JointPhysicsConfig(
        spring_k=250.0, damping_c=18.0, inertia=0.8,
        is_primary=True, gravity_sensitivity=0.0,
        follow_through_strength=0.2, anticipation_strength=0.0,
    ),
}

# Fallback config for joints not in the default profiles
_FALLBACK_CONFIG = JointPhysicsConfig(
    spring_k=200.0, damping_c=15.0, inertia=1.0,
    is_primary=True, gravity_sensitivity=0.0,
)


# ── Cognitive Motion Constraints ──────────────────────────────────────────────


@dataclass
class CognitiveMotionConfig:
    """Global configuration for cognitive motion constraints.

    These encode the 12 Principles of Animation as mathematical rules:
    - Anticipation: brief reverse motion before main action
    - Follow-through: continuation after main motion stops
    - Overlapping action: different parts move at different rates
    - Squash & Stretch: volume preservation during deformation
    """
    # Global enable/disable
    enable_anticipation: bool = True
    enable_follow_through: bool = True
    enable_overlapping: bool = True

    # Squash & Stretch (applied as scale hints in the output)
    enable_squash_stretch: bool = True
    max_squash: float = 0.75  # Minimum Y scale
    max_stretch: float = 1.25  # Maximum Y scale
    volume_preservation: bool = True  # If True, X*Y ≈ 1.0

    # Global strength multiplier
    strength: float = 1.0


# ── AnglePoseProjector (Primary Integration Path) ────────────────────────────


class AnglePoseProjector:
    """PhysDiff-inspired angle-space physics projector.

    This is the recommended integration path. It works directly with the
    angle-based pose dicts that the renderer expects, applying spring-damper
    physics to each joint angle independently.

    The "physics projection" concept from PhysDiff is implemented as:
    1. The animation system generates a "target" pose (angles)
    2. Each joint has an angular spring-damper that tracks the target
    3. The spring dynamics naturally produce:
       - Inertia (heavier parts lag behind)
       - Follow-through (parts overshoot and oscillate)
       - Overlapping action (different spring constants = different timing)
    4. Cognitive motion constraints add anticipation and squash/stretch

    Parameters
    ----------
    joint_configs : dict[str, JointPhysicsConfig], optional
        Per-joint physics configuration. Defaults to DEFAULT_JOINT_PHYSICS.
    cognitive_config : CognitiveMotionConfig, optional
        Cognitive motion constraint configuration.
    global_stiffness_scale : float
        Multiplier for all spring stiffness values. Use to globally
        adjust how tightly the physics tracks the animation.
        Range: 0.5 (loose/organic) to 2.0 (tight/snappy).
    global_damping_scale : float
        Multiplier for all damping values.
    """

    def __init__(
        self,
        joint_configs: dict[str, JointPhysicsConfig] | None = None,
        cognitive_config: CognitiveMotionConfig | None = None,
        global_stiffness_scale: float = 1.0,
        global_damping_scale: float = 1.0,
    ):
        self._configs = dict(joint_configs or DEFAULT_JOINT_PHYSICS)
        self._cognitive = cognitive_config or CognitiveMotionConfig()
        self._stiffness_scale = float(np.clip(global_stiffness_scale, 0.1, 10.0))
        self._damping_scale = float(np.clip(global_damping_scale, 0.1, 10.0))

        # Per-joint spring-damper states
        self._states: dict[str, AngularSpringState] = {}

        # History buffer for anticipation detection
        self._target_history: list[dict[str, float]] = []
        self._max_history = 8

        # Frame counter
        self._frame_count: int = 0

        # Delayed target buffers for overlapping action
        self._delayed_targets: dict[str, list[float]] = {}

    def _get_config(self, joint_name: str) -> JointPhysicsConfig:
        """Get physics config for a joint, falling back to default."""
        return self._configs.get(joint_name, _FALLBACK_CONFIG)

    def _get_state(self, joint_name: str, initial_angle: float = 0.0) -> AngularSpringState:
        """Get or create spring state for a joint."""
        if joint_name not in self._states:
            self._states[joint_name] = AngularSpringState(
                angle=initial_angle,
                angular_velocity=0.0,
                prev_target=initial_angle,
            )
        return self._states[joint_name]

    def step(
        self,
        raw_pose: dict[str, float],
        dt: float = 1.0 / 60.0,
    ) -> dict[str, float]:
        """Project a single pose through the physics engine.

        This is the core "physics projection" step, analogous to PhysDiff's
        per-step physics simulation projection.

        Parameters
        ----------
        raw_pose : dict[str, float]
            Raw animation pose (joint_name → angle in radians).
        dt : float
            Timestep in seconds.

        Returns
        -------
        dict[str, float] : Physics-corrected pose.
        """
        self._frame_count += 1

        # Store target history for anticipation detection
        self._target_history.append(dict(raw_pose))
        if len(self._target_history) > self._max_history:
            self._target_history.pop(0)

        corrected_pose: dict[str, float] = {}

        for joint_name, target_angle in raw_pose.items():
            config = self._get_config(joint_name)
            state = self._get_state(joint_name, target_angle)

            # Apply overlapping action delay
            effective_target = self._apply_overlap_delay(
                joint_name, target_angle, config, dt
            )

            # Apply anticipation
            if self._cognitive.enable_anticipation and config.anticipation_strength > 0:
                effective_target = self._apply_anticipation(
                    joint_name, effective_target, config
                )

            # Angular spring-damper simulation
            corrected_angle = self._simulate_angular_spring(
                state, effective_target, config, dt
            )

            # Apply follow-through
            if self._cognitive.enable_follow_through and config.follow_through_strength > 0:
                corrected_angle = self._apply_follow_through(
                    state, corrected_angle, config, dt
                )

            corrected_pose[joint_name] = corrected_angle
            state.prev_target = target_angle

        return corrected_pose

    def step_with_metadata(
        self,
        raw_pose: dict[str, float],
        dt: float = 1.0 / 60.0,
    ) -> tuple[dict[str, float], dict[str, float]]:
        """Project a pose and return both corrected pose and squash/stretch hints.

        Returns
        -------
        (corrected_pose, metadata) where metadata contains:
            - "squash_stretch_y": Y scale factor for squash/stretch
            - "squash_stretch_x": X scale factor (volume-preserving)
            - "velocity_magnitude": overall motion speed estimate
        """
        corrected_pose = self.step(raw_pose, dt)

        # Compute velocity-based squash/stretch
        metadata = {}
        if self._cognitive.enable_squash_stretch and len(self._target_history) >= 2:
            velocity = self._estimate_velocity()
            ss_y, ss_x = self._compute_squash_stretch(velocity)
            metadata["squash_stretch_y"] = ss_y
            metadata["squash_stretch_x"] = ss_x
            metadata["velocity_magnitude"] = velocity
        else:
            metadata["squash_stretch_y"] = 1.0
            metadata["squash_stretch_x"] = 1.0
            metadata["velocity_magnitude"] = 0.0

        return corrected_pose, metadata

    def project_sequence(
        self,
        pose_sequence: list[dict[str, float]],
        dt: float = 1.0 / 60.0,
    ) -> list[dict[str, float]]:
        """Project an entire animation sequence through the physics engine.

        Parameters
        ----------
        pose_sequence : list of dict[str, float]
            Sequence of raw poses (one per frame).
        dt : float
            Timestep between frames.

        Returns
        -------
        list of dict[str, float] : Corrected pose sequence.
        """
        self.reset()
        return [self.step(pose, dt) for pose in pose_sequence]

    def reset(self) -> None:
        """Reset all physics states (call when starting a new animation)."""
        self._states.clear()
        self._target_history.clear()
        self._delayed_targets.clear()
        self._frame_count = 0

    # ── Physics Simulation Sub-steps ──

    def _simulate_angular_spring(
        self,
        state: AngularSpringState,
        target: float,
        config: JointPhysicsConfig,
        dt: float,
    ) -> float:
        """Simulate one step of the angular spring-damper.

        Equation of motion:
            I * α = -k * (θ - θ_target) - c * ω + τ_gravity

        Uses semi-implicit Euler integration for stability.
        """
        k = config.spring_k * self._stiffness_scale
        c = config.damping_c * self._damping_scale
        I = config.inertia

        # Angular displacement from target
        displacement = state.angle - target

        # Normalize displacement to [-π, π] to handle angle wrapping
        while displacement > math.pi:
            displacement -= 2 * math.pi
        while displacement < -math.pi:
            displacement += 2 * math.pi

        # Spring torque: -k * displacement
        torque_spring = -k * displacement

        # Damping torque: -c * angular_velocity
        torque_damping = -c * state.angular_velocity

        # Gravity torque (simplified: acts as a downward bias on arms/head)
        torque_gravity = config.gravity_sensitivity * self._cognitive.strength * (-2.0)

        # Total torque → angular acceleration
        total_torque = torque_spring + torque_damping + torque_gravity
        angular_acceleration = total_torque / I

        # Semi-implicit Euler integration
        state.angular_velocity += angular_acceleration * dt
        state.angle += state.angular_velocity * dt

        return state.angle

    def _apply_anticipation(
        self,
        joint_name: str,
        target: float,
        config: JointPhysicsConfig,
    ) -> float:
        """Apply anticipation: brief reverse motion before a large movement.

        Detects sudden target changes and adds a small reverse offset.
        """
        if len(self._target_history) < 3:
            return target

        # Detect sudden velocity change in target
        prev_targets = [
            h.get(joint_name, target) for h in self._target_history[-3:]
        ]
        target_accel = prev_targets[-1] - 2 * prev_targets[-2] + prev_targets[-3]

        # If acceleration is large, apply anticipation (reverse offset)
        if abs(target_accel) > 0.05:
            anticipation_offset = -target_accel * config.anticipation_strength
            return target + anticipation_offset

        return target

    def _apply_follow_through(
        self,
        state: AngularSpringState,
        corrected_angle: float,
        config: JointPhysicsConfig,
        dt: float,
    ) -> float:
        """Apply follow-through: allow overshoot when target stops moving.

        When the target stops changing, the spring naturally overshoots.
        This method amplifies that effect based on follow_through_strength.
        """
        # Check if target has stopped (velocity near zero)
        target_velocity = state.prev_target - (
            self._target_history[-2].get(state.prev_target, state.prev_target)
            if len(self._target_history) >= 2 and isinstance(state.prev_target, str)
            else 0.0
        )

        # The spring-damper naturally produces follow-through.
        # We amplify it by slightly reducing damping when overshoot is detected.
        overshoot = state.angular_velocity
        if abs(overshoot) > 0.01:
            # Allow more overshoot for secondary joints
            amplification = 1.0 + config.follow_through_strength * 0.3
            corrected_angle += overshoot * dt * (amplification - 1.0)

        return corrected_angle

    def _apply_overlap_delay(
        self,
        joint_name: str,
        target: float,
        config: JointPhysicsConfig,
        dt: float,
    ) -> float:
        """Apply overlapping action: delay target for secondary joints.

        Secondary joints receive their targets with a small delay,
        causing them to lag behind primary joints naturally.
        """
        if not self._cognitive.enable_overlapping or config.overlap_delay <= 0:
            return target

        # Maintain a buffer of recent targets for this joint
        if joint_name not in self._delayed_targets:
            self._delayed_targets[joint_name] = []

        buffer = self._delayed_targets[joint_name]
        buffer.append(target)

        # Calculate how many frames of delay
        delay_frames = max(1, int(config.overlap_delay / max(dt, 1e-6)))
        max_buffer = delay_frames + 2

        if len(buffer) > max_buffer:
            buffer.pop(0)

        # Return the delayed target
        if len(buffer) > delay_frames:
            return buffer[-delay_frames - 1]
        return buffer[0]

    def _estimate_velocity(self) -> float:
        """Estimate overall motion velocity from target history."""
        if len(self._target_history) < 2:
            return 0.0

        current = self._target_history[-1]
        previous = self._target_history[-2]

        total_delta = 0.0
        count = 0
        for joint_name in current:
            if joint_name in previous:
                delta = abs(current[joint_name] - previous[joint_name])
                total_delta += delta
                count += 1

        return total_delta / max(count, 1)

    def _compute_squash_stretch(self, velocity: float) -> tuple[float, float]:
        """Compute squash/stretch scale factors from velocity.

        Returns (y_scale, x_scale) where x*y ≈ 1.0 for volume preservation.
        """
        # Map velocity to stretch factor
        # Higher velocity → more stretch (taller, thinner)
        stretch_factor = 1.0 + velocity * 2.0 * self._cognitive.strength

        # Clamp to configured range
        y_scale = float(np.clip(
            stretch_factor,
            self._cognitive.max_squash,
            self._cognitive.max_stretch,
        ))

        # Volume preservation: x * y ≈ 1.0
        if self._cognitive.volume_preservation:
            x_scale = 1.0 / y_scale
        else:
            x_scale = 1.0

        return y_scale, x_scale


# ── Position-Based Physics Projector (Advanced Path) ──────────────────────────


@dataclass
class Particle:
    """A 2D particle for Verlet integration.

    Represents a skeletal joint in the physics simulation.
    Uses position-based dynamics: velocity is implicit in (pos - old_pos).
    """
    name: str
    pos: np.ndarray = field(default_factory=lambda: np.zeros(2))
    old_pos: np.ndarray = field(default_factory=lambda: np.zeros(2))
    acceleration: np.ndarray = field(default_factory=lambda: np.zeros(2))
    mass: float = 1.0
    is_pinned: bool = False

    @property
    def velocity(self) -> np.ndarray:
        return self.pos - self.old_pos

    def apply_force(self, force: np.ndarray) -> None:
        if self.mass > 1e-8 and not self.is_pinned:
            self.acceleration = self.acceleration + force / self.mass


@dataclass
class DistanceConstraint:
    """Maintains fixed distance between two particles (bone length preservation)."""
    p1_idx: int
    p2_idx: int
    rest_length: float
    stiffness: float = 1.0


@dataclass
class GroundConstraint:
    """Prevents particles from penetrating the ground plane."""
    particle_idx: int
    ground_y: float = 0.0
    friction: float = 0.3


class PositionPhysicsProjector:
    """Full Verlet integration physics projector with IK back-conversion.

    This is the advanced integration path. It simulates physics in position
    space using Verlet integration and PBD constraints, then converts the
    corrected positions back to joint angles for the renderer.

    Parameters
    ----------
    gravity : tuple[float, float]
        Gravity vector. Default (0, -9.8).
    solver_iterations : int
        PBD constraint relaxation iterations. Range: 4-16.
    damping : float
        Global velocity damping. Range: 0.95-0.999.
    """

    def __init__(
        self,
        gravity: tuple[float, float] = (0.0, -9.8),
        solver_iterations: int = 8,
        damping: float = 0.98,
    ):
        self.gravity = np.array(gravity, dtype=float)
        self.solver_iterations = int(np.clip(solver_iterations, 1, 64))
        self.damping = float(np.clip(damping, 0.8, 1.0))

        self.particles: list[Particle] = []
        self.distance_constraints: list[DistanceConstraint] = []
        self.ground_constraints: list[GroundConstraint] = []

        self._name_to_idx: dict[str, int] = {}
        self._initialized = False

    def init_from_skeleton(
        self,
        skeleton,
        pinned_joints: set[str] | None = None,
        ground_joints: set[str] | None = None,
    ) -> None:
        """Initialize physics particles from a Skeleton object."""
        if pinned_joints is None:
            pinned_joints = {"root", "hip", "spine", "chest"}
        if ground_joints is None:
            ground_joints = {"l_foot", "r_foot"}

        self.particles.clear()
        self.distance_constraints.clear()
        self.ground_constraints.clear()
        self._name_to_idx.clear()

        # Create particles
        for i, (name, joint) in enumerate(skeleton.joints.items()):
            p = Particle(
                name=name,
                pos=np.array([joint.x, joint.y], dtype=float),
                old_pos=np.array([joint.x, joint.y], dtype=float),
                mass=1.0 if name not in pinned_joints else 0.0,
                is_pinned=(name in pinned_joints),
            )
            self.particles.append(p)
            self._name_to_idx[name] = i

        # Create distance constraints from bones
        for bone in skeleton.bones:
            if bone.joint_a in self._name_to_idx and bone.joint_b in self._name_to_idx:
                self.distance_constraints.append(DistanceConstraint(
                    p1_idx=self._name_to_idx[bone.joint_a],
                    p2_idx=self._name_to_idx[bone.joint_b],
                    rest_length=bone.length,
                ))

        # Create ground constraints
        for name in ground_joints:
            if name in self._name_to_idx:
                self.ground_constraints.append(GroundConstraint(
                    particle_idx=self._name_to_idx[name],
                    ground_y=0.0,
                ))

        self._initialized = True

    def step(
        self,
        target_positions: dict[str, tuple[float, float]],
        dt: float = 1.0 / 60.0,
    ) -> dict[str, tuple[float, float]]:
        """Advance physics by one timestep and return corrected positions."""
        if not self._initialized:
            return dict(target_positions)

        # Sync pinned particles
        for name, pos in target_positions.items():
            if name in self._name_to_idx:
                idx = self._name_to_idx[name]
                p = self.particles[idx]
                if p.is_pinned:
                    p.old_pos = p.pos.copy()
                    p.pos = np.array(pos, dtype=float)

        # Apply gravity
        for p in self.particles:
            if not p.is_pinned and p.mass > 1e-8:
                p.apply_force(self.gravity * p.mass)

        # Apply target attraction for non-pinned particles
        for name, pos in target_positions.items():
            if name in self._name_to_idx:
                idx = self._name_to_idx[name]
                p = self.particles[idx]
                if not p.is_pinned and p.mass > 1e-8:
                    target = np.array(pos, dtype=float)
                    force = 25.0 * (target - p.pos) * p.mass
                    p.apply_force(force)

        # Verlet integration
        for p in self.particles:
            if p.is_pinned:
                p.acceleration = np.zeros(2)
                continue
            velocity = p.pos - p.old_pos
            new_pos = p.pos + velocity * self.damping + p.acceleration * dt * dt
            p.old_pos = p.pos.copy()
            p.pos = new_pos
            p.acceleration = np.zeros(2)

        # Constraint relaxation
        for _ in range(self.solver_iterations):
            self._solve_distance_constraints()
            self._solve_ground_constraints()

        return {p.name: (float(p.pos[0]), float(p.pos[1])) for p in self.particles}

    def _solve_distance_constraints(self) -> None:
        for dc in self.distance_constraints:
            p1 = self.particles[dc.p1_idx]
            p2 = self.particles[dc.p2_idx]
            delta = p2.pos - p1.pos
            dist = float(np.linalg.norm(delta))
            if dist < 1e-8:
                continue
            diff = (dc.rest_length - dist) / dist
            correction = delta * diff * 0.5 * dc.stiffness
            w1 = 0.0 if p1.is_pinned else 1.0 / max(p1.mass, 1e-8)
            w2 = 0.0 if p2.is_pinned else 1.0 / max(p2.mass, 1e-8)
            total_w = w1 + w2
            if total_w < 1e-8:
                continue
            p1.pos -= correction * (w1 / total_w)
            p2.pos += correction * (w2 / total_w)

    def _solve_ground_constraints(self) -> None:
        for gc in self.ground_constraints:
            p = self.particles[gc.particle_idx]
            if p.pos[1] < gc.ground_y:
                p.pos[1] = gc.ground_y
                if gc.friction > 0:
                    h_vel = p.pos[0] - p.old_pos[0]
                    p.old_pos[0] = p.pos[0] - h_vel * (1.0 - gc.friction)

    def positions_to_angles(
        self,
        positions: dict[str, tuple[float, float]],
        skeleton,
    ) -> dict[str, float]:
        """Convert corrected joint positions back to joint angles.

        Uses inverse trigonometry to compute the angle each bone makes
        relative to its parent, which is what the renderer expects.
        """
        angles: dict[str, float] = {}

        for name, joint in skeleton.joints.items():
            if joint.parent is None or name == "root":
                continue
            if name not in positions or joint.parent not in positions:
                continue

            parent_pos = np.array(positions[joint.parent])
            child_pos = np.array(positions[name])

            # Compute angle of the bone relative to the default orientation
            delta = child_pos - parent_pos
            current_angle = math.atan2(float(delta[1]), float(delta[0]))

            # Default bone direction
            default_dx = joint.x - skeleton.joints[joint.parent].x
            default_dy = joint.y - skeleton.joints[joint.parent].y
            default_angle = math.atan2(default_dy, default_dx)

            # The joint angle is the difference from default
            joint_angle = current_angle - default_angle

            # Normalize to [-π, π]
            while joint_angle > math.pi:
                joint_angle -= 2 * math.pi
            while joint_angle < -math.pi:
                joint_angle += 2 * math.pi

            # Clamp to ROM
            joint_angle = float(np.clip(joint_angle, joint.min_angle, joint.max_angle))

            angles[name] = joint_angle

        return angles


# ── Physics-Aware Fitness Functions ───────────────────────────────────────────


def compute_physics_penalty(
    pose_sequence: list[dict[str, float]],
    skeleton,
    dt: float = 1.0 / 60.0,
    weights: dict[str, float] | None = None,
) -> float:
    """Compute a physics-based penalty score for an animation sequence.

    Encodes physical constraints as differentiable penalty functions,
    suitable for integration into genetic algorithm fitness evaluation.
    Inspired by PINNs (Physics-Informed Neural Networks).

    Parameters
    ----------
    pose_sequence : list of dict[str, float]
        Animation sequence as joint angles per frame.
    skeleton : Skeleton
        The skeleton definition with bone lengths and joint ROM.
    dt : float
        Timestep between frames.
    weights : dict[str, float], optional
        Penalty weights. Keys: "smoothness", "rom", "symmetry", "energy".

    Returns
    -------
    float : Total physics penalty (lower is better, 0 = physically perfect).
    """
    if not pose_sequence or len(pose_sequence) < 2:
        return 0.0

    default_weights = {
        "smoothness": 5.0,   # Penalize jerk (sudden acceleration changes)
        "rom": 10.0,         # Penalize ROM violations
        "symmetry": 2.0,     # Penalize asymmetric motion (for idle/walk)
        "energy": 1.0,       # Penalize excessive energy expenditure
    }
    w = {**default_weights, **(weights or {})}

    total_penalty = 0.0
    n_frames = len(pose_sequence)

    for frame_idx in range(n_frames):
        frame = pose_sequence[frame_idx]

        # ROM violation penalty
        for joint_name, angle in frame.items():
            if joint_name in skeleton.joints:
                joint = skeleton.joints[joint_name]
                if angle < joint.min_angle:
                    diff = joint.min_angle - angle
                    total_penalty += w["rom"] * diff * diff
                elif angle > joint.max_angle:
                    diff = angle - joint.max_angle
                    total_penalty += w["rom"] * diff * diff

    # Smoothness penalty (jerk minimization)
    if n_frames >= 3:
        for joint_name in pose_sequence[0]:
            angles = [frame.get(joint_name, 0.0) for frame in pose_sequence]
            for i in range(1, len(angles) - 1):
                # Second derivative (acceleration)
                accel = angles[i + 1] - 2 * angles[i] + angles[i - 1]
                total_penalty += w["smoothness"] * accel * accel

    # Symmetry penalty (left-right pairs should be somewhat symmetric for idle)
    symmetric_pairs = [
        ("l_shoulder", "r_shoulder"),
        ("l_elbow", "r_elbow"),
        ("l_hip", "r_hip"),
        ("l_knee", "r_knee"),
    ]
    for frame in pose_sequence:
        for left, right in symmetric_pairs:
            if left in frame and right in frame:
                # Penalize large asymmetry
                diff = abs(frame[left] + frame[right])  # Should sum to ~0 for symmetric
                total_penalty += w["symmetry"] * diff * diff * 0.1

    # Energy penalty (penalize large angular velocities)
    if n_frames >= 2:
        for joint_name in pose_sequence[0]:
            for i in range(1, n_frames):
                prev = pose_sequence[i - 1].get(joint_name, 0.0)
                curr = pose_sequence[i].get(joint_name, 0.0)
                velocity = (curr - prev) / dt
                total_penalty += w["energy"] * velocity * velocity * 0.0001

    return total_penalty / max(n_frames, 1)


# ── Convenience: Enhanced Easing Functions (Robert Penner) ────────────────────


def ease_in_quad(t: float) -> float:
    """Quadratic ease-in: slow start."""
    return t * t


def ease_out_quad(t: float) -> float:
    """Quadratic ease-out: slow end."""
    return t * (2.0 - t)


def ease_in_out_quad(t: float) -> float:
    """Quadratic ease-in-out: slow start and end."""
    if t < 0.5:
        return 2.0 * t * t
    return -1.0 + (4.0 - 2.0 * t) * t


def ease_in_cubic(t: float) -> float:
    """Cubic ease-in."""
    return t * t * t


def ease_out_cubic(t: float) -> float:
    """Cubic ease-out."""
    t1 = t - 1.0
    return t1 * t1 * t1 + 1.0


def ease_in_out_cubic(t: float) -> float:
    """Cubic ease-in-out."""
    if t < 0.5:
        return 4.0 * t * t * t
    return (t - 1.0) * (2.0 * t - 2.0) * (2.0 * t - 2.0) + 1.0


def ease_in_elastic(t: float) -> float:
    """Elastic ease-in: spring-like overshoot at start."""
    if t <= 0.0 or t >= 1.0:
        return t
    return -math.pow(2, 10 * (t - 1)) * math.sin((t - 1.1) * 5 * math.pi)


def ease_out_elastic(t: float) -> float:
    """Elastic ease-out: spring-like overshoot at end."""
    if t <= 0.0 or t >= 1.0:
        return t
    return math.pow(2, -10 * t) * math.sin((t - 0.1) * 5 * math.pi) + 1.0


def ease_out_back(t: float, overshoot: float = 1.70158) -> float:
    """Back ease-out: slight overshoot past target."""
    t1 = t - 1.0
    return t1 * t1 * ((overshoot + 1.0) * t1 + overshoot) + 1.0


def ease_in_back(t: float, overshoot: float = 1.70158) -> float:
    """Back ease-in: slight pull-back before moving forward."""
    return t * t * ((overshoot + 1.0) * t - overshoot)


PENNER_EASING_FUNCTIONS: dict[str, callable] = {
    "ease_in_quad": ease_in_quad,
    "ease_out_quad": ease_out_quad,
    "ease_in_out_quad": ease_in_out_quad,
    "ease_in_cubic": ease_in_cubic,
    "ease_out_cubic": ease_out_cubic,
    "ease_in_out_cubic": ease_in_out_cubic,
    "ease_in_elastic": ease_in_elastic,
    "ease_out_elastic": ease_out_elastic,
    "ease_out_back": ease_out_back,
    "ease_in_back": ease_in_back,
}
