"""Physics Projector — PhysDiff-inspired physics projection for 2D skeletal animation.

Inspired by PhysDiff (ICCV 2023), this module implements a lightweight 2D physics
engine based on Verlet integration and Position-Based Dynamics (PBD). It acts as a
post-processing layer that "projects" raw animation poses into a physically plausible
subspace, eliminating artifacts like foot sliding, ground penetration, and unnatural
stiffness.

**Critical design decision**: The existing renderer (`render_character_frame`) works
with angle-based pose dicts (`dict[str, float]`). This module therefore provides TWO
integration paths:

1. **AnglePoseProjector** (recommended): Works directly in angle space. It applies
   spring-damper physics to joint angles, producing smooth, physically-motivated
   secondary motion without breaking the renderer contract.

2. **PositionPhysicsProjector**: Works in position space using full Verlet integration
   and PBD. Converts corrected positions back to angles via inverse kinematics.
   More physically accurate but heavier.

Architecture overview (PhysDiff → 2D migration):
  1. Raw pose generated by existing animation system (presets.py, IK, etc.)
  2. Projector receives the raw pose and applies physics corrections
  3. Corrected pose returned as dict[str, float] for rendering

Mathematical foundations:
  - Verlet Integration: x(t+dt) = x(t) + (x(t) - x(t-dt)) + a(t)*dt²
  - PBD Distance Constraint: Δx = (|x2-x1| - L₀) / |x2-x1| * (x2-x1) * 0.5
  - Spring-Damper: F = -k*(θ - θ_target) - c*ω (angular spring)
  - Ground Constraint: if foot_y < ground_y then correct leg angles
  - Cognitive Motion: anticipation, follow-through, overlapping action

References:
  - PhysDiff: https://arxiv.org/abs/2212.02500
  - Jakobsen, "Advanced Character Physics" (GDC 2001)
  - Pikuma, "Verlet Integration and Cloth Physics Simulation"

Usage::

    from mathart.animation.physics_projector import AnglePoseProjector

    projector = AnglePoseProjector()

    # In the animation loop:
    raw_pose = idle_animation(t)
    corrected_pose = projector.step(raw_pose, dt=1/60)
    # corrected_pose is a dict[str, float] — same contract as raw_pose
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field, replace
from typing import Optional, Callable

import numpy as np

from .unified_motion import UnifiedMotionFrame, umr_to_pose


# ── Angular Spring-Damper State ───────────────────────────────────────────────


@dataclass
class AngularSpringState:
    """State of an angular spring-damper for a single joint.

    Uses the equation of motion:
        I * α = -k * (θ - θ_target) - c * ω + τ_ext

    where:
        I = moment of inertia
        k = angular spring stiffness
        c = angular damping coefficient
        θ = current angle
        ω = angular velocity (dθ/dt)
        θ_target = target angle from animation
        τ_ext = external torque (gravity, etc.)
    """
    angle: float = 0.0
    angular_velocity: float = 0.0
    prev_target: float = 0.0


@dataclass
class JointPhysicsConfig:
    """Physics configuration for a single joint.

    Parameters
    ----------
    spring_k : float
        Angular spring stiffness. Higher = snappier tracking.
        Range: 50-500 for primary joints, 10-50 for secondary.
    damping_c : float
        Angular damping. Higher = less oscillation.
        Range: 5-30.
    inertia : float
        Moment of inertia. Higher = more sluggish response.
        Range: 0.5-5.0.
    is_primary : bool
        If True, this joint closely follows the animation target.
        If False, it has more freedom to exhibit secondary motion.
    gravity_sensitivity : float
        How much this joint is affected by gravity torque.
        Range: 0.0-1.0. Arms/head should be higher.
    follow_through_strength : float
        Strength of follow-through effect (continuation after stop).
        Range: 0.0-1.0.
    anticipation_strength : float
        Strength of anticipation (brief reverse before main motion).
        Range: 0.0-0.3.
    overlap_delay : float
        Delay in seconds for overlapping action.
        Range: 0.0-0.1.
    """
    spring_k: float = 200.0
    damping_c: float = 15.0
    inertia: float = 1.0
    is_primary: bool = True
    gravity_sensitivity: float = 0.0
    follow_through_strength: float = 0.0
    anticipation_strength: float = 0.0
    overlap_delay: float = 0.0


# ── Default Joint Physics Profiles ────────────────────────────────────────────

# These profiles encode the "personality" of each joint's physics behavior.
# Primary joints (spine, hips, knees) track the animation tightly.
# Secondary joints (head, hands, elbows) have more freedom for natural motion.

DEFAULT_JOINT_PHYSICS: dict[str, JointPhysicsConfig] = {
    # Spine chain: tight tracking, minimal secondary motion
    "hip": JointPhysicsConfig(
        spring_k=350.0, damping_c=22.0, inertia=2.5,
        is_primary=True, gravity_sensitivity=0.0,
        follow_through_strength=0.05, anticipation_strength=0.03,
    ),
    "spine": JointPhysicsConfig(
        spring_k=300.0, damping_c=20.0, inertia=2.0,
        is_primary=True, gravity_sensitivity=0.0,
        follow_through_strength=0.1, anticipation_strength=0.05,
    ),
    "chest": JointPhysicsConfig(
        spring_k=280.0, damping_c=18.0, inertia=1.8,
        is_primary=True, gravity_sensitivity=0.0,
        follow_through_strength=0.15, anticipation_strength=0.05,
    ),
    "neck": JointPhysicsConfig(
        spring_k=150.0, damping_c=12.0, inertia=0.8,
        is_primary=False, gravity_sensitivity=0.1,
        follow_through_strength=0.3, anticipation_strength=0.1,
    ),
    "head": JointPhysicsConfig(
        spring_k=120.0, damping_c=10.0, inertia=1.2,
        is_primary=False, gravity_sensitivity=0.15,
        follow_through_strength=0.4, anticipation_strength=0.1,
        overlap_delay=0.03,
    ),

    # Arms: moderate tracking, good secondary motion
    "l_shoulder": JointPhysicsConfig(
        spring_k=180.0, damping_c=14.0, inertia=1.0,
        is_primary=False, gravity_sensitivity=0.2,
        follow_through_strength=0.35, anticipation_strength=0.08,
        overlap_delay=0.02,
    ),
    "r_shoulder": JointPhysicsConfig(
        spring_k=180.0, damping_c=14.0, inertia=1.0,
        is_primary=False, gravity_sensitivity=0.2,
        follow_through_strength=0.35, anticipation_strength=0.08,
        overlap_delay=0.02,
    ),
    "l_elbow": JointPhysicsConfig(
        spring_k=100.0, damping_c=8.0, inertia=0.6,
        is_primary=False, gravity_sensitivity=0.3,
        follow_through_strength=0.5, anticipation_strength=0.0,
        overlap_delay=0.04,
    ),
    "r_elbow": JointPhysicsConfig(
        spring_k=100.0, damping_c=8.0, inertia=0.6,
        is_primary=False, gravity_sensitivity=0.3,
        follow_through_strength=0.5, anticipation_strength=0.0,
        overlap_delay=0.04,
    ),
    "l_hand": JointPhysicsConfig(
        spring_k=60.0, damping_c=5.0, inertia=0.3,
        is_primary=False, gravity_sensitivity=0.4,
        follow_through_strength=0.6, anticipation_strength=0.0,
        overlap_delay=0.06,
    ),
    "r_hand": JointPhysicsConfig(
        spring_k=60.0, damping_c=5.0, inertia=0.3,
        is_primary=False, gravity_sensitivity=0.4,
        follow_through_strength=0.6, anticipation_strength=0.0,
        overlap_delay=0.06,
    ),

    # Legs: tight tracking (critical for locomotion)
    "l_hip": JointPhysicsConfig(
        spring_k=350.0, damping_c=22.0, inertia=1.5,
        is_primary=True, gravity_sensitivity=0.0,
        follow_through_strength=0.1, anticipation_strength=0.05,
    ),
    "r_hip": JointPhysicsConfig(
        spring_k=350.0, damping_c=22.0, inertia=1.5,
        is_primary=True, gravity_sensitivity=0.0,
        follow_through_strength=0.1, anticipation_strength=0.05,
    ),
    "l_knee": JointPhysicsConfig(
        spring_k=320.0, damping_c=20.0, inertia=1.2,
        is_primary=True, gravity_sensitivity=0.0,
        follow_through_strength=0.15, anticipation_strength=0.0,
    ),
    "r_knee": JointPhysicsConfig(
        spring_k=320.0, damping_c=20.0, inertia=1.2,
        is_primary=True, gravity_sensitivity=0.0,
        follow_through_strength=0.15, anticipation_strength=0.0,
    ),
    "l_foot": JointPhysicsConfig(
        spring_k=250.0, damping_c=18.0, inertia=0.8,
        is_primary=True, gravity_sensitivity=0.0,
        follow_through_strength=0.2, anticipation_strength=0.0,
    ),
    "r_foot": JointPhysicsConfig(
        spring_k=250.0, damping_c=18.0, inertia=0.8,
        is_primary=True, gravity_sensitivity=0.0,
        follow_through_strength=0.2, anticipation_strength=0.0,
    ),
}

# Fallback config for joints not in the default profiles
_FALLBACK_CONFIG = JointPhysicsConfig(
    spring_k=200.0, damping_c=15.0, inertia=1.0,
    is_primary=True, gravity_sensitivity=0.0,
)


# ── Cognitive Motion Constraints ──────────────────────────────────────────────


@dataclass
class CognitiveMotionConfig:
    """Global configuration for cognitive motion constraints.

    These encode the 12 Principles of Animation as mathematical rules:
    - Anticipation: brief reverse motion before main action
    - Follow-through: continuation after main motion stops
    - Overlapping action: different parts move at different rates
    - Squash & Stretch: volume preservation during deformation
    """
    # Global enable/disable
    enable_anticipation: bool = True
    enable_follow_through: bool = True
    enable_overlapping: bool = True

    # Squash & Stretch (applied as scale hints in the output)
    enable_squash_stretch: bool = True
    max_squash: float = 0.75  # Minimum Y scale
    max_stretch: float = 1.25  # Maximum Y scale
    volume_preservation: bool = True  # If True, X*Y ≈ 1.0

    # Global strength multiplier
    strength: float = 1.0


# ── AnglePoseProjector (Primary Integration Path) ────────────────────────────


class AnglePoseProjector:
    """PhysDiff-inspired angle-space physics projector.

    This is the recommended integration path. It works directly with the
    angle-based pose dicts that the renderer expects, applying physics
    to each joint angle independently.

    SESSION-035 UPGRADE: Two physics modes are now available:

    1. **"spring" mode** (legacy): Rigid spring-damper that forces exact
       pose matching. Can create "Frankenstein" artifacts when the source
       motion deviates significantly from the target.

    2. **"compliant_pd" mode** (NEW, default): DeepMimic-inspired compliant
       PD servo tracking. The physics layer acts as a *soft guide* rather
       than a rigid corrector. Key properties:
       - Compliance parameter α ∈ [0,1] controls how much the physics
         "trusts" the upstream motion vs. enforcing its own corrections
       - Per-joint compliance: primary joints (legs) track tightly,
         secondary joints (arms, head) have more artistic freedom
       - Gravity-aware balance: compensates gravity without overriding
         the motion's artistic intent
       - DeepMimic reward-weighted blending: the tracking strength is
         modulated by how well the current pose matches the reference

    Reference: Peng et al., "DeepMimic: Example-Guided Deep Reinforcement
    Learning of Physics-Based Character Skills" (SIGGRAPH 2018)
    - PD control law: τ = k_p * (θ_target - θ_current) - k_d * ω_current
    - The PD controller does NOT override motion — it TRACKS with compliance

    Parameters
    ----------
    joint_configs : dict[str, JointPhysicsConfig], optional
        Per-joint physics configuration. Defaults to DEFAULT_JOINT_PHYSICS.
    cognitive_config : CognitiveMotionConfig, optional
        Cognitive motion constraint configuration.
    global_stiffness_scale : float
        Multiplier for all spring stiffness values. Use to globally
        adjust how tightly the physics tracks the animation.
        Range: 0.5 (loose/organic) to 2.0 (tight/snappy).
    global_damping_scale : float
        Multiplier for all damping values.
    compliance_mode : str
        Physics simulation mode. "compliant_pd" (default, DeepMimic-style
        soft tracking) or "spring" (legacy rigid spring-damper).
    compliance_alpha : float
        Global compliance factor [0, 1]. 0 = physics fully trusts upstream
        motion (pass-through), 1 = physics fully controls (rigid tracking).
        Default 0.6 — physics provides gentle guidance while preserving
        the upstream motion's artistic character.
    """

    # SESSION-035: Per-joint compliance factors (DeepMimic-inspired)
    # Primary joints track tightly (high compliance), secondary joints
    # preserve artistic freedom (low compliance)
    _JOINT_COMPLIANCE: dict[str, float] = {
        # Legs: tight tracking — critical for locomotion stability
        "l_hip": 0.85, "r_hip": 0.85,
        "l_knee": 0.80, "r_knee": 0.80,
        "l_foot": 0.75, "r_foot": 0.75,
        # Spine: moderate — balance matters but allow artistic expression
        "hip": 0.70, "spine": 0.65, "chest": 0.60,
        # Head/neck: loose — let upstream motion shine
        "neck": 0.40, "head": 0.35,
        # Arms: loose — secondary motion should feel organic
        "l_shoulder": 0.45, "r_shoulder": 0.45,
        "l_elbow": 0.35, "r_elbow": 0.35,
        "l_hand": 0.25, "r_hand": 0.25,
    }

    def __init__(
        self,
        joint_configs: dict[str, JointPhysicsConfig] | None = None,
        cognitive_config: CognitiveMotionConfig | None = None,
        global_stiffness_scale: float = 1.0,
        global_damping_scale: float = 1.0,
        enable_foot_locking: bool = True,
        skeleton_ref=None,
        compliance_mode: str = "compliant_pd",
        compliance_alpha: float = 0.6,
    ):
        self._configs = dict(joint_configs or DEFAULT_JOINT_PHYSICS)
        self._cognitive = cognitive_config or CognitiveMotionConfig()
        self._stiffness_scale = float(np.clip(global_stiffness_scale, 0.1, 10.0))
        self._damping_scale = float(np.clip(global_damping_scale, 0.1, 10.0))

        # SESSION-035: Compliance mode selection
        self._compliance_mode = compliance_mode if compliance_mode in ("compliant_pd", "spring") else "compliant_pd"
        self._compliance_alpha = float(np.clip(compliance_alpha, 0.0, 1.0))

        # Per-joint spring-damper states
        self._states: dict[str, AngularSpringState] = {}

        # History buffer for anticipation detection
        self._target_history: list[dict[str, float]] = []
        self._max_history = 8

        # Frame counter
        self._frame_count: int = 0

        # Delayed target buffers for overlapping action
        self._delayed_targets: dict[str, list[float]] = {}

        # SESSION-028-SUPP: PhysDiff-inspired foot contact & skating cleanup
        self._enable_foot_locking = enable_foot_locking
        self._contact_detector = ContactDetector()
        self._constraint_blender = ConstraintBlender(blend_in_frames=3, blend_out_frames=4)
        self._foot_locker = FootLockingConstraint(skeleton_ref=skeleton_ref)
        self._skeleton_ref = skeleton_ref

    def _get_config(self, joint_name: str) -> JointPhysicsConfig:
        """Get physics config for a joint, falling back to default."""
        return self._configs.get(joint_name, _FALLBACK_CONFIG)

    def _get_state(self, joint_name: str, initial_angle: float = 0.0) -> AngularSpringState:
        """Get or create spring state for a joint."""
        if joint_name not in self._states:
            self._states[joint_name] = AngularSpringState(
                angle=initial_angle,
                angular_velocity=0.0,
                prev_target=initial_angle,
            )
        return self._states[joint_name]

    def step(
        self,
        raw_pose: dict[str, float],
        dt: float = 1.0 / 60.0,
    ) -> dict[str, float]:
        """Project a single pose through the physics engine.

        This is the core "physics projection" step, analogous to PhysDiff's
        per-step physics simulation projection.

        Parameters
        ----------
        raw_pose : dict[str, float]
            Raw animation pose (joint_name → angle in radians).
        dt : float
            Timestep in seconds.

        Returns
        -------
        dict[str, float] : Physics-corrected pose.
        """
        self._frame_count += 1

        # Store target history for anticipation detection
        self._target_history.append(dict(raw_pose))
        if len(self._target_history) > self._max_history:
            self._target_history.pop(0)

        corrected_pose: dict[str, float] = {}

        for joint_name, target_angle in raw_pose.items():
            config = self._get_config(joint_name)
            state = self._get_state(joint_name, target_angle)

            # Apply overlapping action delay
            effective_target = self._apply_overlap_delay(
                joint_name, target_angle, config, dt
            )

            # Apply anticipation
            if self._cognitive.enable_anticipation and config.anticipation_strength > 0:
                effective_target = self._apply_anticipation(
                    joint_name, effective_target, config
                )

            # SESSION-035: Physics simulation — mode-dependent
            if self._compliance_mode == "compliant_pd":
                corrected_angle = self._simulate_compliant_pd(
                    joint_name, state, effective_target, config, dt
                )
            else:
                # Legacy spring-damper mode
                corrected_angle = self._simulate_angular_spring(
                    state, effective_target, config, dt
                )

            # Apply follow-through
            if self._cognitive.enable_follow_through and config.follow_through_strength > 0:
                corrected_angle = self._apply_follow_through(
                    state, corrected_angle, config, dt
                )

            corrected_pose[joint_name] = corrected_angle
            state.prev_target = target_angle

        # SESSION-028-SUPP: PhysDiff-inspired foot contact & skating cleanup
        if self._enable_foot_locking and self._skeleton_ref is not None:
            corrected_pose = self._apply_foot_locking(corrected_pose, dt)

        return corrected_pose

    def _apply_foot_locking(
        self,
        pose: dict[str, float],
        dt: float,
    ) -> dict[str, float]:
        """Apply foot-locking constraint to eliminate skating artifacts.

        This is the 2D equivalent of PhysDiff's physics-based motion projection
        specifically targeting foot sliding. The process is:
        1. Run FK to get current foot world positions
        2. Detect contact states (height + velocity heuristic)
        3. Compute blend weights (smooth transitions)
        4. Apply IK corrections to lock feet at contact points
        """
        skeleton = self._skeleton_ref

        # Step 1: Forward kinematics to get world positions
        skeleton.apply_pose(pose)
        joint_positions = skeleton.forward_kinematics()

        # Step 2: Update contact detection
        contact_states = self._contact_detector.update(joint_positions, dt)

        # Step 3: Compute blend weights for smooth transitions
        blend_weights = {}
        for foot_name, state in contact_states.items():
            blend_weights[foot_name] = self._constraint_blender.compute_weight(state)

        # Step 4: Apply IK-based foot locking
        corrected = self._foot_locker.correct_pose(
            pose, contact_states, blend_weights, joint_positions, skeleton
        )

        return corrected

    def step_with_metadata(
        self,
        raw_pose: dict[str, float],
        dt: float = 1.0 / 60.0,
    ) -> tuple[dict[str, float], dict[str, float]]:
        """Project a pose and return both corrected pose and squash/stretch hints.

        Returns
        -------
        (corrected_pose, metadata) where metadata contains:
            - "squash_stretch_y": Y scale factor for squash/stretch
            - "squash_stretch_x": X scale factor (volume-preserving)
            - "velocity_magnitude": overall motion speed estimate
        """
        corrected_pose = self.step(raw_pose, dt)

        # Compute velocity-based squash/stretch
        metadata = {}
        if self._cognitive.enable_squash_stretch and len(self._target_history) >= 2:
            velocity = self._estimate_velocity()
            ss_y, ss_x = self._compute_squash_stretch(velocity)
            metadata["squash_stretch_y"] = ss_y
            metadata["squash_stretch_x"] = ss_x
            metadata["velocity_magnitude"] = velocity
        else:
            metadata["squash_stretch_y"] = 1.0
            metadata["squash_stretch_x"] = 1.0
            metadata["velocity_magnitude"] = 0.0

        return corrected_pose, metadata

    def project_sequence(
        self,
        pose_sequence: list[dict[str, float]],
        dt: float = 1.0 / 60.0,
    ) -> list[dict[str, float]]:
        """Project an entire animation sequence through the physics engine."""
        self.reset()
        return [self.step(pose, dt) for pose in pose_sequence]

    def step_frame(
        self,
        frame: UnifiedMotionFrame,
        dt: float = 1.0 / 60.0,
        *,
        enforce_layer_guard: bool = True,
    ) -> UnifiedMotionFrame:
        """Project a UMR frame through physics while respecting layer boundaries.

        The physics layer is allowed to refine locomotion-critical joints, but it
        must not hijack high-level expressive animation. Therefore the frame API
        optionally clamps per-joint deltas more aggressively on upper-body joints.
        """
        raw_pose = umr_to_pose(frame)
        corrected_pose, metadata = self.step_with_metadata(raw_pose, dt=dt)

        if enforce_layer_guard:
            guarded_pose: dict[str, float] = {}
            for joint, raw_angle in raw_pose.items():
                corrected_angle = float(corrected_pose.get(joint, raw_angle))
                delta = corrected_angle - float(raw_angle)
                if joint in {"hip", "l_hip", "r_hip", "l_knee", "r_knee", "l_foot", "r_foot"}:
                    max_delta = 0.18
                elif joint in {"spine", "chest"}:
                    max_delta = 0.06
                else:
                    max_delta = 0.035
                guarded_pose[joint] = float(raw_angle) + max(-max_delta, min(max_delta, delta))
            corrected_pose = guarded_pose

        merged_metadata = dict(frame.metadata)
        merged_metadata.update({
            "physics_projected": True,
            "physics_stage": "compliance_filter",
            "physics_layer_guard": bool(enforce_layer_guard),
            "physics_joint_count": len(corrected_pose),
            "physics_debug": metadata,
        })
        return replace(
            frame,
            joint_local_rotations=corrected_pose,
            metadata=merged_metadata,
        )

    def project_frame_sequence(
        self,
        frames: list[UnifiedMotionFrame],
        dt: float = 1.0 / 60.0,
        *,
        enforce_layer_guard: bool = True,
    ) -> list[UnifiedMotionFrame]:
        """Project an entire UMR sequence through the physics engine."""
        self.reset()
        return [self.step_frame(frame, dt=dt, enforce_layer_guard=enforce_layer_guard) for frame in frames]

    def reset(self) -> None:
        """Reset all physics states (call when starting a new animation)."""
        self._states.clear()
        self._target_history.clear()
        self._delayed_targets.clear()
        self._frame_count = 0
        # SESSION-028-SUPP: Reset foot contact states
        self._contact_detector.reset()
        for name in self._contact_detector.foot_joints:
            self._contact_detector._states[name] = ContactState()

    # ── Physics Simulation Sub-steps ──

    def _simulate_compliant_pd(
        self,
        joint_name: str,
        state: AngularSpringState,
        target: float,
        config: JointPhysicsConfig,
        dt: float,
    ) -> float:
        """SESSION-035: DeepMimic-inspired compliant PD servo tracking.

        Unlike the rigid spring-damper, this method implements a *compliant*
        PD controller that respects the upstream motion's artistic intent.

        The key insight from DeepMimic (Peng et al., 2018):
        > The PD controller acts as a compliant servo — it applies torques
        > proportional to the error, with damping proportional to velocity.
        > It does NOT override motion; it TRACKS with compliance.

        Algorithm:
        1. Compute PD torque: τ = k_p * (θ_target - θ_current) - k_d * ω
        2. Apply gravity compensation: τ_g = m * g * L * sin(θ)
        3. Clamp torque to realistic bounds (virtual muscle limits)
        4. Integrate with semi-implicit Euler
        5. Blend result with upstream target using per-joint compliance α:
           θ_final = (1 - α_eff) * θ_target + α_eff * θ_physics

        The compliance blending is the critical difference from the legacy
        spring-damper: it ensures the physics layer *guides* rather than
        *overrides* the upstream motion.

        Parameters
        ----------
        joint_name : str
            Joint name for per-joint compliance lookup.
        state : AngularSpringState
            Current angular state of this joint.
        target : float
            Target angle from upstream animation.
        config : JointPhysicsConfig
            Per-joint physics configuration.
        dt : float
            Timestep in seconds.

        Returns
        -------
        float : Compliant-PD-corrected angle.
        """
        # ── Step 1: PD torque computation (DeepMimic Eq. 4) ──
        k_p = config.spring_k * self._stiffness_scale
        k_d = config.damping_c * self._damping_scale
        I = config.inertia

        # Angular error with wrapping to [-π, π]
        error = target - state.angle
        while error > math.pi:
            error -= 2 * math.pi
        while error < -math.pi:
            error += 2 * math.pi

        # Core PD law: τ = k_p * error - k_d * ω
        tau_pd = k_p * error - k_d * state.angular_velocity

        # ── Step 2: Gravity compensation (DeepMimic Section 4) ──
        tau_gravity = config.gravity_sensitivity * self._cognitive.strength * (-2.0)

        # ── Step 3: Torque clamping (virtual muscle limits) ──
        # Max torque proportional to k_p (stronger muscles = more torque)
        max_torque = k_p * 1.5
        total_torque = float(np.clip(tau_pd + tau_gravity, -max_torque, max_torque))

        # ── Step 4: Semi-implicit Euler integration ──
        alpha_phys = total_torque / max(I, 1e-8)
        state.angular_velocity += alpha_phys * dt

        # Velocity damping (prevents energy accumulation)
        state.angular_velocity *= 0.98

        theta_physics = state.angle + state.angular_velocity * dt

        # ── Step 5: Compliance blending (SESSION-035 core innovation) ──
        # α_eff = global_alpha * per_joint_alpha
        # Low α → trust upstream motion (artistic freedom)
        # High α → trust physics (stability enforcement)
        per_joint_alpha = self._JOINT_COMPLIANCE.get(joint_name, 0.5)
        alpha_eff = self._compliance_alpha * per_joint_alpha

        # Blend: final = (1 - α) * upstream_target + α * physics_result
        theta_final = (1.0 - alpha_eff) * target + alpha_eff * theta_physics

        # Update state for next frame
        state.angle = theta_final

        return theta_final

    def _simulate_angular_spring(
        self,
        state: AngularSpringState,
        target: float,
        config: JointPhysicsConfig,
        dt: float,
    ) -> float:
        """Simulate one step of the angular spring-damper.

        Equation of motion:
            I * α = -k * (θ - θ_target) - c * ω + τ_gravity

        Uses semi-implicit Euler integration for stability.
        """
        k = config.spring_k * self._stiffness_scale
        c = config.damping_c * self._damping_scale
        I = config.inertia

        # Angular displacement from target
        displacement = state.angle - target

        # Normalize displacement to [-π, π] to handle angle wrapping
        while displacement > math.pi:
            displacement -= 2 * math.pi
        while displacement < -math.pi:
            displacement += 2 * math.pi

        # Spring torque: -k * displacement
        torque_spring = -k * displacement

        # Damping torque: -c * angular_velocity
        torque_damping = -c * state.angular_velocity

        # Gravity torque (simplified: acts as a downward bias on arms/head)
        torque_gravity = config.gravity_sensitivity * self._cognitive.strength * (-2.0)

        # Total torque → angular acceleration
        total_torque = torque_spring + torque_damping + torque_gravity
        angular_acceleration = total_torque / I

        # Semi-implicit Euler integration
        state.angular_velocity += angular_acceleration * dt
        state.angle += state.angular_velocity * dt

        return state.angle

    def _apply_anticipation(
        self,
        joint_name: str,
        target: float,
        config: JointPhysicsConfig,
    ) -> float:
        """Apply anticipation: brief reverse motion before a large movement.

        Detects sudden target changes and adds a small reverse offset.
        """
        if len(self._target_history) < 3:
            return target

        # Detect sudden velocity change in target
        prev_targets = [
            h.get(joint_name, target) for h in self._target_history[-3:]
        ]
        target_accel = prev_targets[-1] - 2 * prev_targets[-2] + prev_targets[-3]

        # If acceleration is large, apply anticipation (reverse offset)
        if abs(target_accel) > 0.05:
            anticipation_offset = -target_accel * config.anticipation_strength
            return target + anticipation_offset

        return target

    def _apply_follow_through(
        self,
        state: AngularSpringState,
        corrected_angle: float,
        config: JointPhysicsConfig,
        dt: float,
    ) -> float:
        """Apply follow-through: allow overshoot when target stops moving.

        When the target stops changing, the spring naturally overshoots.
        This method amplifies that effect based on follow_through_strength.
        """
        # Check if target has stopped (velocity near zero)
        target_velocity = state.prev_target - (
            self._target_history[-2].get(state.prev_target, state.prev_target)
            if len(self._target_history) >= 2 and isinstance(state.prev_target, str)
            else 0.0
        )

        # The spring-damper naturally produces follow-through.
        # We amplify it by slightly reducing damping when overshoot is detected.
        overshoot = state.angular_velocity
        if abs(overshoot) > 0.01:
            # Allow more overshoot for secondary joints
            amplification = 1.0 + config.follow_through_strength * 0.3
            corrected_angle += overshoot * dt * (amplification - 1.0)

        return corrected_angle

    def _apply_overlap_delay(
        self,
        joint_name: str,
        target: float,
        config: JointPhysicsConfig,
        dt: float,
    ) -> float:
        """Apply overlapping action: delay target for secondary joints.

        Secondary joints receive their targets with a small delay,
        causing them to lag behind primary joints naturally.
        """
        if not self._cognitive.enable_overlapping or config.overlap_delay <= 0:
            return target

        # Maintain a buffer of recent targets for this joint
        if joint_name not in self._delayed_targets:
            self._delayed_targets[joint_name] = []

        buffer = self._delayed_targets[joint_name]
        buffer.append(target)

        # Calculate how many frames of delay
        delay_frames = max(1, int(config.overlap_delay / max(dt, 1e-6)))
        max_buffer = delay_frames + 2

        if len(buffer) > max_buffer:
            buffer.pop(0)

        # Return the delayed target
        if len(buffer) > delay_frames:
            return buffer[-delay_frames - 1]
        return buffer[0]

    def _estimate_velocity(self) -> float:
        """Estimate overall motion velocity from target history."""
        if len(self._target_history) < 2:
            return 0.0

        current = self._target_history[-1]
        previous = self._target_history[-2]

        total_delta = 0.0
        count = 0
        for joint_name in current:
            if joint_name in previous:
                delta = abs(current[joint_name] - previous[joint_name])
                total_delta += delta
                count += 1

        return total_delta / max(count, 1)

    def _compute_squash_stretch(self, velocity: float) -> tuple[float, float]:
        """Compute squash/stretch scale factors from velocity.

        Returns (y_scale, x_scale) where x*y ≈ 1.0 for volume preservation.
        """
        # Map velocity to stretch factor
        # Higher velocity → more stretch (taller, thinner)
        stretch_factor = 1.0 + velocity * 2.0 * self._cognitive.strength

        # Clamp to configured range
        y_scale = float(np.clip(
            stretch_factor,
            self._cognitive.max_squash,
            self._cognitive.max_stretch,
        ))

        # Volume preservation: x * y ≈ 1.0
        if self._cognitive.volume_preservation:
            x_scale = 1.0 / y_scale
        else:
            x_scale = 1.0

        return y_scale, x_scale


# ── Position-Based Physics Projector (Advanced Path) ──────────────────────────


@dataclass
class Particle:
    """A 2D particle for Verlet integration.

    Represents a skeletal joint in the physics simulation.
    Uses position-based dynamics: velocity is implicit in (pos - old_pos).
    """
    name: str
    pos: np.ndarray = field(default_factory=lambda: np.zeros(2))
    old_pos: np.ndarray = field(default_factory=lambda: np.zeros(2))
    acceleration: np.ndarray = field(default_factory=lambda: np.zeros(2))
    mass: float = 1.0
    is_pinned: bool = False

    @property
    def velocity(self) -> np.ndarray:
        return self.pos - self.old_pos

    def apply_force(self, force: np.ndarray) -> None:
        if self.mass > 1e-8 and not self.is_pinned:
            self.acceleration = self.acceleration + force / self.mass


@dataclass
class DistanceConstraint:
    """Maintains fixed distance between two particles (bone length preservation)."""
    p1_idx: int
    p2_idx: int
    rest_length: float
    stiffness: float = 1.0


@dataclass
class GroundConstraint:
    """Prevents particles from penetrating the ground plane."""
    particle_idx: int
    ground_y: float = 0.0
    friction: float = 0.3


class PositionPhysicsProjector:
    """Full Verlet integration physics projector with IK back-conversion.

    This is the advanced integration path. It simulates physics in position
    space using Verlet integration and PBD constraints, then converts the
    corrected positions back to joint angles for the renderer.

    Parameters
    ----------
    gravity : tuple[float, float]
        Gravity vector. Default (0, -9.8).
    solver_iterations : int
        PBD constraint relaxation iterations. Range: 4-16.
    damping : float
        Global velocity damping. Range: 0.95-0.999.
    """

    def __init__(
        self,
        gravity: tuple[float, float] = (0.0, -9.8),
        solver_iterations: int = 8,
        damping: float = 0.98,
    ):
        self.gravity = np.array(gravity, dtype=float)
        self.solver_iterations = int(np.clip(solver_iterations, 1, 64))
        self.damping = float(np.clip(damping, 0.8, 1.0))

        self.particles: list[Particle] = []
        self.distance_constraints: list[DistanceConstraint] = []
        self.ground_constraints: list[GroundConstraint] = []

        self._name_to_idx: dict[str, int] = {}
        self._initialized = False

    def init_from_skeleton(
        self,
        skeleton,
        pinned_joints: set[str] | None = None,
        ground_joints: set[str] | None = None,
    ) -> None:
        """Initialize physics particles from a Skeleton object."""
        if pinned_joints is None:
            pinned_joints = {"root", "hip", "spine", "chest"}
        if ground_joints is None:
            ground_joints = {"l_foot", "r_foot"}

        self.particles.clear()
        self.distance_constraints.clear()
        self.ground_constraints.clear()
        self._name_to_idx.clear()

        # Create particles
        for i, (name, joint) in enumerate(skeleton.joints.items()):
            p = Particle(
                name=name,
                pos=np.array([joint.x, joint.y], dtype=float),
                old_pos=np.array([joint.x, joint.y], dtype=float),
                mass=1.0 if name not in pinned_joints else 0.0,
                is_pinned=(name in pinned_joints),
            )
            self.particles.append(p)
            self._name_to_idx[name] = i

        # Create distance constraints from bones
        for bone in skeleton.bones:
            if bone.joint_a in self._name_to_idx and bone.joint_b in self._name_to_idx:
                self.distance_constraints.append(DistanceConstraint(
                    p1_idx=self._name_to_idx[bone.joint_a],
                    p2_idx=self._name_to_idx[bone.joint_b],
                    rest_length=bone.length,
                ))

        # Create ground constraints
        for name in ground_joints:
            if name in self._name_to_idx:
                self.ground_constraints.append(GroundConstraint(
                    particle_idx=self._name_to_idx[name],
                    ground_y=0.0,
                ))

        self._initialized = True

    def step(
        self,
        target_positions: dict[str, tuple[float, float]],
        dt: float = 1.0 / 60.0,
    ) -> dict[str, tuple[float, float]]:
        """Advance physics by one timestep and return corrected positions."""
        if not self._initialized:
            return dict(target_positions)

        # Sync pinned particles
        for name, pos in target_positions.items():
            if name in self._name_to_idx:
                idx = self._name_to_idx[name]
                p = self.particles[idx]
                if p.is_pinned:
                    p.old_pos = p.pos.copy()
                    p.pos = np.array(pos, dtype=float)

        # Apply gravity
        for p in self.particles:
            if not p.is_pinned and p.mass > 1e-8:
                p.apply_force(self.gravity * p.mass)

        # Apply target attraction for non-pinned particles
        for name, pos in target_positions.items():
            if name in self._name_to_idx:
                idx = self._name_to_idx[name]
                p = self.particles[idx]
                if not p.is_pinned and p.mass > 1e-8:
                    target = np.array(pos, dtype=float)
                    force = 25.0 * (target - p.pos) * p.mass
                    p.apply_force(force)

        # Verlet integration
        for p in self.particles:
            if p.is_pinned:
                p.acceleration = np.zeros(2)
                continue
            velocity = p.pos - p.old_pos
            new_pos = p.pos + velocity * self.damping + p.acceleration * dt * dt
            p.old_pos = p.pos.copy()
            p.pos = new_pos
            p.acceleration = np.zeros(2)

        # Constraint relaxation
        for _ in range(self.solver_iterations):
            self._solve_distance_constraints()
            self._solve_ground_constraints()

        return {p.name: (float(p.pos[0]), float(p.pos[1])) for p in self.particles}

    def _solve_distance_constraints(self) -> None:
        for dc in self.distance_constraints:
            p1 = self.particles[dc.p1_idx]
            p2 = self.particles[dc.p2_idx]
            delta = p2.pos - p1.pos
            dist = float(np.linalg.norm(delta))
            if dist < 1e-8:
                continue
            diff = (dc.rest_length - dist) / dist
            correction = delta * diff * 0.5 * dc.stiffness
            w1 = 0.0 if p1.is_pinned else 1.0 / max(p1.mass, 1e-8)
            w2 = 0.0 if p2.is_pinned else 1.0 / max(p2.mass, 1e-8)
            total_w = w1 + w2
            if total_w < 1e-8:
                continue
            p1.pos -= correction * (w1 / total_w)
            p2.pos += correction * (w2 / total_w)

    def _solve_ground_constraints(self) -> None:
        for gc in self.ground_constraints:
            p = self.particles[gc.particle_idx]
            if p.pos[1] < gc.ground_y:
                p.pos[1] = gc.ground_y
                if gc.friction > 0:
                    h_vel = p.pos[0] - p.old_pos[0]
                    p.old_pos[0] = p.pos[0] - h_vel * (1.0 - gc.friction)

    def positions_to_angles(
        self,
        positions: dict[str, tuple[float, float]],
        skeleton,
    ) -> dict[str, float]:
        """Convert corrected joint positions back to joint angles.

        Uses inverse trigonometry to compute the angle each bone makes
        relative to its parent, which is what the renderer expects.
        """
        angles: dict[str, float] = {}

        for name, joint in skeleton.joints.items():
            if joint.parent is None or name == "root":
                continue
            if name not in positions or joint.parent not in positions:
                continue

            parent_pos = np.array(positions[joint.parent])
            child_pos = np.array(positions[name])

            # Compute angle of the bone relative to the default orientation
            delta = child_pos - parent_pos
            current_angle = math.atan2(float(delta[1]), float(delta[0]))

            # Default bone direction
            default_dx = joint.x - skeleton.joints[joint.parent].x
            default_dy = joint.y - skeleton.joints[joint.parent].y
            default_angle = math.atan2(default_dy, default_dx)

            # The joint angle is the difference from default
            joint_angle = current_angle - default_angle

            # Normalize to [-π, π]
            while joint_angle > math.pi:
                joint_angle -= 2 * math.pi
            while joint_angle < -math.pi:
                joint_angle += 2 * math.pi

            # Clamp to ROM
            joint_angle = float(np.clip(joint_angle, joint.min_angle, joint.max_angle))

            angles[name] = joint_angle

        return angles


# ── PhysDiff-Inspired Foot Contact & Skating Cleanup ──────────────────────────
#
# These classes implement the core mechanisms from PhysDiff (ICCV 2023) that were
# missing in the initial SESSION-028 delivery:
#   1. ContactDetector: detects when feet touch the ground (height + velocity heuristic)
#   2. FootLockingConstraint: locks foot position during ground contact via IK
#   3. ConstraintBlender: smoothly blends constraints on/off to avoid popping
#   4. FootSkatingPenalty: explicit skating metric for GA fitness integration
#
# Reference: Yuan et al., "PhysDiff: Physics-Guided Human Motion Diffusion Model"
#   - Foot Skating metric: "find foot joints that contact the ground in two adjacent
#     frames and compute their average horizontal displacement" (Appendix A)
#   - Kovar et al., "Footskate Cleanup for Motion Capture Editing" (SCA 2002)


@dataclass
class ContactState:
    """Tracks the contact state of a single foot joint.

    Attributes
    ----------
    is_contacting : bool
        Whether the foot is currently in ground contact.
    contact_point : tuple[float, float] or None
        The world-space position where the foot first made contact.
        While contacting, the foot should be locked to this point.
    blend_weight : float
        Current blending weight for the IK constraint (0.0 = free, 1.0 = locked).
    frames_in_contact : int
        Number of consecutive frames the foot has been in contact.
    frames_since_release : int
        Number of frames since the foot left the ground.
    """
    is_contacting: bool = False
    contact_point: Optional[tuple[float, float]] = None
    blend_weight: float = 0.0
    frames_in_contact: int = 0
    frames_since_release: int = 0


class ContactDetector:
    """Detects foot-ground contact using height and velocity heuristics.

    Inspired by PhysDiff's implicit contact handling through physics simulation,
    adapted for our 2D kinematic pipeline where we need explicit detection.

    The detection uses two criteria (both must be satisfied):
      1. Height criterion: foot_y <= contact_threshold
      2. Velocity criterion: |foot_vy| <= velocity_threshold (foot nearly stationary)

    Parameters
    ----------
    contact_threshold : float
        Maximum height (in normalized skeleton units) for a foot to be
        considered "on the ground". Default 0.05 (5% of character height).
    velocity_threshold : float
        Maximum vertical velocity magnitude for contact detection.
        Default 0.15 (allows slow descent but rejects fast swings).
    foot_joints : list[str]
        Names of foot joints to monitor. Default ["l_foot", "r_foot"].
    """

    def __init__(
        self,
        contact_threshold: float = 0.05,
        velocity_threshold: float = 0.15,
        foot_joints: list[str] | None = None,
    ):
        self.contact_threshold = contact_threshold
        self.velocity_threshold = velocity_threshold
        self.foot_joints = foot_joints or ["l_foot", "r_foot"]

        self._states: dict[str, ContactState] = {
            name: ContactState() for name in self.foot_joints
        }
        self._prev_positions: dict[str, tuple[float, float]] = {}

    def update(
        self,
        joint_positions: dict[str, tuple[float, float]],
        dt: float = 1.0 / 60.0,
    ) -> dict[str, ContactState]:
        """Update contact states based on current joint world positions.

        Parameters
        ----------
        joint_positions : dict[str, (x, y)]
            World-space positions of all joints (from forward kinematics).
        dt : float
            Timestep for velocity computation.

        Returns
        -------
        dict[str, ContactState] : Current contact state per foot joint.
        """
        for foot_name in self.foot_joints:
            if foot_name not in joint_positions:
                continue

            pos = joint_positions[foot_name]
            state = self._states[foot_name]
            foot_y = pos[1]

            # Compute vertical velocity
            vy = 0.0
            if foot_name in self._prev_positions:
                prev_y = self._prev_positions[foot_name][1]
                vy = (foot_y - prev_y) / max(dt, 1e-8)

            # Contact detection: height below threshold AND velocity small
            height_ok = foot_y <= self.contact_threshold
            velocity_ok = abs(vy) <= self.velocity_threshold
            now_contacting = height_ok and velocity_ok

            if now_contacting and not state.is_contacting:
                # Transition: free → contact
                state.is_contacting = True
                state.contact_point = (pos[0], min(pos[1], 0.0))
                state.frames_in_contact = 1
                state.frames_since_release = 0
            elif now_contacting and state.is_contacting:
                # Continuing contact
                state.frames_in_contact += 1
            elif not now_contacting and state.is_contacting:
                # Transition: contact → free
                state.is_contacting = False
                state.frames_since_release = 1
                state.frames_in_contact = 0
            else:
                # Continuing free
                state.frames_since_release += 1
                state.contact_point = None

            self._prev_positions[foot_name] = pos

        return dict(self._states)

    def reset(self) -> None:
        """Reset all contact states."""
        for name in self.foot_joints:
            self._states[name] = ContactState()
        self._prev_positions.clear()


class ConstraintBlender:
    """Smoothly blends IK constraint weights during contact transitions.

    Prevents visual "popping" when foot constraints turn on/off, as described
    in Kovar et al. (2002). The blend weight ramps up over `blend_in_frames`
    when contact begins, and ramps down over `blend_out_frames` when contact ends.

    Parameters
    ----------
    blend_in_frames : int
        Number of frames to ramp constraint weight from 0 to 1 on contact start.
    blend_out_frames : int
        Number of frames to ramp constraint weight from 1 to 0 on contact end.
    """

    def __init__(self, blend_in_frames: int = 3, blend_out_frames: int = 4):
        self.blend_in_frames = max(1, blend_in_frames)
        self.blend_out_frames = max(1, blend_out_frames)

    def compute_weight(self, contact_state: ContactState) -> float:
        """Compute the current blend weight for a foot's IK constraint.

        Returns a value in [0.0, 1.0] where:
          0.0 = foot is completely free (no IK correction)
          1.0 = foot is fully locked to contact point
        """
        if contact_state.is_contacting:
            # Ramping up: smoothstep over blend_in_frames
            t = min(contact_state.frames_in_contact / self.blend_in_frames, 1.0)
            weight = self._smoothstep(t)
        else:
            # Ramping down: smoothstep over blend_out_frames
            if contact_state.frames_since_release <= self.blend_out_frames:
                t = 1.0 - min(
                    contact_state.frames_since_release / self.blend_out_frames, 1.0
                )
                weight = self._smoothstep(t)
            else:
                weight = 0.0

        contact_state.blend_weight = weight
        return weight

    @staticmethod
    def _smoothstep(t: float) -> float:
        """Hermite smoothstep: 3t² - 2t³ for C¹ continuous transitions."""
        t = float(np.clip(t, 0.0, 1.0))
        return t * t * (3.0 - 2.0 * t)


class FootLockingConstraint:
    """Locks foot positions during ground contact by adjusting leg joint angles.

    This is the 2D equivalent of PhysDiff's physics-based motion projection for
    foot skating elimination. When a foot is detected as contacting the ground,
    this constraint computes the necessary leg angle corrections to keep the foot
    at its contact point, using analytical 2-bone IK (hip→knee→foot).

    The constraint works in angle space (compatible with the renderer) by:
    1. Computing where the foot WOULD be given current angles (via FK)
    2. Computing where the foot SHOULD be (the contact point)
    3. Solving 2-bone IK for the leg to reach the contact point
    4. Blending the IK-corrected angles with the original angles

    Parameters
    ----------
    leg_chains : dict[str, tuple[str, str, str]]
        Mapping from foot joint name to (hip_joint, knee_joint, foot_joint).
    skeleton_ref : object or None
        Reference skeleton for bone length lookup. If None, uses default lengths.
    """

    # Default leg chain definitions for humanoid skeleton
    DEFAULT_LEG_CHAINS: dict[str, tuple[str, str, str]] = {
        "l_foot": ("l_hip", "l_knee", "l_foot"),
        "r_foot": ("r_hip", "r_knee", "r_foot"),
    }

    def __init__(
        self,
        leg_chains: dict[str, tuple[str, str, str]] | None = None,
        skeleton_ref=None,
    ):
        self.leg_chains = leg_chains or self.DEFAULT_LEG_CHAINS
        self._bone_lengths: dict[str, tuple[float, float]] = {}

        # Pre-compute bone lengths from skeleton if available
        if skeleton_ref is not None:
            self._init_bone_lengths(skeleton_ref)

    def _init_bone_lengths(self, skeleton) -> None:
        """Extract thigh and shin bone lengths from skeleton definition."""
        for foot_name, (hip_name, knee_name, foot_name_) in self.leg_chains.items():
            thigh_len = 0.0
            shin_len = 0.0
            for bone in skeleton.bones:
                if bone.joint_a == hip_name and bone.joint_b == knee_name:
                    thigh_len = bone.length
                elif bone.joint_a == knee_name and bone.joint_b == foot_name_:
                    shin_len = bone.length
            if thigh_len > 0 and shin_len > 0:
                self._bone_lengths[foot_name] = (thigh_len, shin_len)

    def correct_pose(
        self,
        pose: dict[str, float],
        contact_states: dict[str, ContactState],
        blend_weights: dict[str, float],
        joint_positions: dict[str, tuple[float, float]],
        skeleton,
    ) -> dict[str, float]:
        """Apply foot-locking corrections to a pose.

        Parameters
        ----------
        pose : dict[str, float]
            Current pose (joint angles) to correct.
        contact_states : dict[str, ContactState]
            Contact states from ContactDetector.
        blend_weights : dict[str, float]
            Blend weights from ConstraintBlender (0=free, 1=locked).
        joint_positions : dict[str, (x, y)]
            Current world positions from FK.
        skeleton : Skeleton
            Skeleton definition for bone lengths and joint info.

        Returns
        -------
        dict[str, float] : Corrected pose with foot-locking applied.
        """
        corrected = dict(pose)

        for foot_name, (hip_name, knee_name, _) in self.leg_chains.items():
            if foot_name not in contact_states:
                continue

            state = contact_states[foot_name]
            weight = blend_weights.get(foot_name, 0.0)

            if weight < 1e-4 or state.contact_point is None:
                continue

            # Get current foot position and target contact point
            if foot_name not in joint_positions or hip_name not in joint_positions:
                continue

            current_foot = joint_positions[foot_name]
            target_foot = state.contact_point

            # Compute horizontal displacement (the "skating" we want to eliminate)
            dx = target_foot[0] - current_foot[0]
            dy = target_foot[1] - current_foot[1]
            displacement = math.sqrt(dx * dx + dy * dy)

            if displacement < 1e-6:
                continue  # Already at contact point

            # Solve 2-bone IK analytically for the leg
            hip_pos = joint_positions[hip_name]
            ik_angles = self._solve_2bone_ik(
                hip_pos, target_foot, foot_name, skeleton
            )

            if ik_angles is None:
                continue

            ik_hip_angle, ik_knee_angle = ik_angles

            # Blend between original angles and IK-corrected angles
            if hip_name in corrected:
                orig_hip = corrected[hip_name]
                corrected[hip_name] = orig_hip + weight * (ik_hip_angle - orig_hip)
            if knee_name in corrected:
                orig_knee = corrected[knee_name]
                corrected[knee_name] = orig_knee + weight * (ik_knee_angle - orig_knee)

        return corrected

    def _solve_2bone_ik(
        self,
        hip_pos: tuple[float, float],
        target: tuple[float, float],
        foot_name: str,
        skeleton,
    ) -> Optional[tuple[float, float]]:
        """Solve 2-bone IK analytically for a leg chain.

        Uses the law of cosines to find hip and knee angles that place
        the foot at the target position.

        Returns (hip_angle, knee_angle) or None if unreachable.
        """
        # Get bone lengths
        if foot_name in self._bone_lengths:
            L1, L2 = self._bone_lengths[foot_name]
        else:
            # Fallback: estimate from skeleton
            chain = self.leg_chains.get(foot_name)
            if chain is None:
                return None
            hip_name, knee_name, foot_name_ = chain
            L1 = L2 = 0.0
            for bone in skeleton.bones:
                if bone.joint_a == hip_name and bone.joint_b == knee_name:
                    L1 = bone.length
                elif bone.joint_a == knee_name and bone.joint_b == foot_name_:
                    L2 = bone.length
            if L1 < 1e-6 or L2 < 1e-6:
                return None
            self._bone_lengths[foot_name] = (L1, L2)

        # Vector from hip to target
        dx = target[0] - hip_pos[0]
        dy = target[1] - hip_pos[1]
        dist = math.sqrt(dx * dx + dy * dy)

        # Clamp distance to reachable range
        max_reach = L1 + L2 - 1e-4
        min_reach = abs(L1 - L2) + 1e-4
        if dist > max_reach:
            dist = max_reach
        elif dist < min_reach:
            dist = min_reach

        # Law of cosines for knee angle
        cos_knee = (L1 * L1 + L2 * L2 - dist * dist) / (2.0 * L1 * L2)
        cos_knee = float(np.clip(cos_knee, -1.0, 1.0))
        knee_angle = -(math.pi - math.acos(cos_knee))  # Negative = backward bend

        # Law of cosines for hip angle
        cos_hip_offset = (L1 * L1 + dist * dist - L2 * L2) / (2.0 * L1 * dist)
        cos_hip_offset = float(np.clip(cos_hip_offset, -1.0, 1.0))
        hip_offset = math.acos(cos_hip_offset)

        # Angle from hip to target
        angle_to_target = math.atan2(dy, dx)

        # Hip angle = angle_to_target ± hip_offset
        # Choose the solution that keeps the knee bending backward
        hip_angle = angle_to_target + hip_offset

        # Convert from world angle to joint-local angle
        # The skeleton's default leg orientation is downward (roughly -π/2)
        # We need to subtract the default bone direction
        default_hip_angle = -math.pi / 2  # Default: straight down
        hip_angle_local = hip_angle - default_hip_angle

        # Normalize angles to [-π, π]
        while hip_angle_local > math.pi:
            hip_angle_local -= 2 * math.pi
        while hip_angle_local < -math.pi:
            hip_angle_local += 2 * math.pi

        return (hip_angle_local, knee_angle)


class PhysDiffProjectionScheduler:
    """Controls when physics projection is applied during iterative generation.

    Inspired by PhysDiff's key finding that applying physics projection at EVERY
    step is suboptimal. The paper found that:
      - More projection steps → better physical plausibility
      - But too many steps → decreased motion quality
      - Late-stage projection works better than early-stage

    In our context, the "diffusion steps" map to GA evolution generations.
    This scheduler determines which generations should apply physics projection.

    Parameters
    ----------
    total_steps : int
        Total number of generation steps (e.g., GA generations).
    projection_ratio : float
        Fraction of steps that should include physics projection.
        Default 0.4 (PhysDiff found ~40% is a good balance).
    late_bias : float
        Bias toward applying projection in later steps.
        0.0 = uniform distribution, 1.0 = all projection in last steps.
        Default 0.7 (PhysDiff found late projection works better).
    """

    def __init__(
        self,
        total_steps: int = 50,
        projection_ratio: float = 0.4,
        late_bias: float = 0.7,
    ):
        self.total_steps = max(1, total_steps)
        self.projection_ratio = float(np.clip(projection_ratio, 0.0, 1.0))
        self.late_bias = float(np.clip(late_bias, 0.0, 1.0))
        self._schedule = self._build_schedule()

    def _build_schedule(self) -> set[int]:
        """Build the set of step indices where projection should be applied."""
        n_projection_steps = max(1, int(self.total_steps * self.projection_ratio))
        schedule = set()

        # Generate step indices with late bias
        for i in range(n_projection_steps):
            # Map i to a position biased toward the end
            t = i / max(1, n_projection_steps - 1) if n_projection_steps > 1 else 1.0
            # Apply late bias: t_biased = t^(1/(1+late_bias))
            # This compresses early steps and expands late steps
            t_biased = math.pow(t, 1.0 / (1.0 + self.late_bias))
            step_idx = int(t_biased * (self.total_steps - 1))
            schedule.add(step_idx)

        return schedule

    def should_project(self, step: int) -> bool:
        """Check if physics projection should be applied at this step."""
        return step in self._schedule

    @property
    def schedule(self) -> list[int]:
        """Return sorted list of steps where projection is applied."""
        return sorted(self._schedule)


# ── Physics-Aware Fitness Functions ───────────────────────────────────────────


def compute_physics_penalty(
    pose_sequence: list[dict[str, float]],
    skeleton,
    dt: float = 1.0 / 60.0,
    weights: dict[str, float] | None = None,
) -> float:
    """Compute a physics-based penalty score for an animation sequence.

    Encodes physical constraints as differentiable penalty functions,
    suitable for integration into genetic algorithm fitness evaluation.
    Inspired by PINNs (Physics-Informed Neural Networks).

    Parameters
    ----------
    pose_sequence : list of dict[str, float]
        Animation sequence as joint angles per frame.
    skeleton : Skeleton
        The skeleton definition with bone lengths and joint ROM.
    dt : float
        Timestep between frames.
    weights : dict[str, float], optional
        Penalty weights. Keys: "smoothness", "rom", "symmetry", "energy".

    Returns
    -------
    float : Total physics penalty (lower is better, 0 = physically perfect).
    """
    if not pose_sequence or len(pose_sequence) < 2:
        return 0.0

    default_weights = {
        "smoothness": 5.0,   # Penalize jerk (sudden acceleration changes)
        "rom": 10.0,         # Penalize ROM violations
        "symmetry": 2.0,     # Penalize asymmetric motion (for idle/walk)
        "energy": 1.0,       # Penalize excessive energy expenditure
    }
    w = {**default_weights, **(weights or {})}

    total_penalty = 0.0
    n_frames = len(pose_sequence)

    for frame_idx in range(n_frames):
        frame = pose_sequence[frame_idx]

        # ROM violation penalty
        for joint_name, angle in frame.items():
            if joint_name in skeleton.joints:
                joint = skeleton.joints[joint_name]
                if angle < joint.min_angle:
                    diff = joint.min_angle - angle
                    total_penalty += w["rom"] * diff * diff
                elif angle > joint.max_angle:
                    diff = angle - joint.max_angle
                    total_penalty += w["rom"] * diff * diff

    # Smoothness penalty (jerk minimization)
    if n_frames >= 3:
        for joint_name in pose_sequence[0]:
            angles = [frame.get(joint_name, 0.0) for frame in pose_sequence]
            for i in range(1, len(angles) - 1):
                # Second derivative (acceleration)
                accel = angles[i + 1] - 2 * angles[i] + angles[i - 1]
                total_penalty += w["smoothness"] * accel * accel

    # Symmetry penalty (left-right pairs should be somewhat symmetric for idle)
    symmetric_pairs = [
        ("l_shoulder", "r_shoulder"),
        ("l_elbow", "r_elbow"),
        ("l_hip", "r_hip"),
        ("l_knee", "r_knee"),
    ]
    for frame in pose_sequence:
        for left, right in symmetric_pairs:
            if left in frame and right in frame:
                # Penalize large asymmetry
                diff = abs(frame[left] + frame[right])  # Should sum to ~0 for symmetric
                total_penalty += w["symmetry"] * diff * diff * 0.1

    # Energy penalty (penalize large angular velocities)
    if n_frames >= 2:
        for joint_name in pose_sequence[0]:
            for i in range(1, n_frames):
                prev = pose_sequence[i - 1].get(joint_name, 0.0)
                curr = pose_sequence[i].get(joint_name, 0.0)
                velocity = (curr - prev) / dt
                total_penalty += w["energy"] * velocity * velocity * 0.0001

    # ── PhysDiff-inspired foot skating penalty (SESSION-028-SUPP) ──
    # "For foot sliding (Skate), we find foot joints that contact the ground
    # in two adjacent frames and compute their average horizontal displacement."
    # — PhysDiff, Appendix A
    foot_joints = ["l_foot", "r_foot"]
    skate_weight = w.get("skating", 8.0)
    penetrate_weight = w.get("penetrate", 10.0)
    float_weight = w.get("float", 3.0)
    contact_threshold = 0.05  # Normalized height threshold

    if n_frames >= 2:
        for frame_idx in range(n_frames):
            pose = pose_sequence[frame_idx]
            skeleton.apply_pose(pose)
            positions = skeleton.forward_kinematics()

            for foot_name in foot_joints:
                if foot_name not in positions:
                    continue
                foot_y = positions[foot_name][1]

                # Ground penetration penalty (PhysDiff: Penetrate metric)
                if foot_y < -0.005:  # 5mm tolerance in normalized units
                    total_penalty += penetrate_weight * foot_y * foot_y

                # Floating penalty (PhysDiff: Float metric)
                # Only penalize if foot SHOULD be grounded but isn't
                # (heuristic: in idle/walk, at least one foot should be near ground)
                if foot_y > 0.15:  # Suspiciously high for a grounded foot
                    total_penalty += float_weight * (foot_y - 0.15) * (foot_y - 0.15) * 0.1

        # Foot skating: horizontal displacement of grounded feet between frames
        for frame_idx in range(1, n_frames):
            prev_pose = pose_sequence[frame_idx - 1]
            curr_pose = pose_sequence[frame_idx]

            skeleton.apply_pose(prev_pose)
            prev_positions = skeleton.forward_kinematics()
            skeleton.apply_pose(curr_pose)
            curr_positions = skeleton.forward_kinematics()

            for foot_name in foot_joints:
                if foot_name not in prev_positions or foot_name not in curr_positions:
                    continue

                prev_y = prev_positions[foot_name][1]
                curr_y = curr_positions[foot_name][1]

                # Both frames: foot is on/near ground
                if prev_y <= contact_threshold and curr_y <= contact_threshold:
                    # Horizontal displacement = skating
                    dx = curr_positions[foot_name][0] - prev_positions[foot_name][0]
                    total_penalty += skate_weight * dx * dx

    return total_penalty / max(n_frames, 1)


# ── Convenience: Enhanced Easing Functions (Robert Penner) ────────────────────


def ease_in_quad(t: float) -> float:
    """Quadratic ease-in: slow start."""
    return t * t


def ease_out_quad(t: float) -> float:
    """Quadratic ease-out: slow end."""
    return t * (2.0 - t)


def ease_in_out_quad(t: float) -> float:
    """Quadratic ease-in-out: slow start and end."""
    if t < 0.5:
        return 2.0 * t * t
    return -1.0 + (4.0 - 2.0 * t) * t


def ease_in_cubic(t: float) -> float:
    """Cubic ease-in."""
    return t * t * t


def ease_out_cubic(t: float) -> float:
    """Cubic ease-out."""
    t1 = t - 1.0
    return t1 * t1 * t1 + 1.0


def ease_in_out_cubic(t: float) -> float:
    """Cubic ease-in-out."""
    if t < 0.5:
        return 4.0 * t * t * t
    return (t - 1.0) * (2.0 * t - 2.0) * (2.0 * t - 2.0) + 1.0


def ease_in_elastic(t: float) -> float:
    """Elastic ease-in: spring-like overshoot at start."""
    if t <= 0.0 or t >= 1.0:
        return t
    return -math.pow(2, 10 * (t - 1)) * math.sin((t - 1.1) * 5 * math.pi)


def ease_out_elastic(t: float) -> float:
    """Elastic ease-out: spring-like overshoot at end."""
    if t <= 0.0 or t >= 1.0:
        return t
    return math.pow(2, -10 * t) * math.sin((t - 0.1) * 5 * math.pi) + 1.0


def ease_out_back(t: float, overshoot: float = 1.70158) -> float:
    """Back ease-out: slight overshoot past target."""
    t1 = t - 1.0
    return t1 * t1 * ((overshoot + 1.0) * t1 + overshoot) + 1.0


def ease_in_back(t: float, overshoot: float = 1.70158) -> float:
    """Back ease-in: slight pull-back before moving forward."""
    return t * t * ((overshoot + 1.0) * t - overshoot)


PENNER_EASING_FUNCTIONS: dict[str, callable] = {
    "ease_in_quad": ease_in_quad,
    "ease_out_quad": ease_out_quad,
    "ease_in_out_quad": ease_in_out_quad,
    "ease_in_cubic": ease_in_cubic,
    "ease_out_cubic": ease_out_cubic,
    "ease_in_out_cubic": ease_in_out_cubic,
    "ease_in_elastic": ease_in_elastic,
    "ease_out_elastic": ease_out_elastic,
    "ease_out_back": ease_out_back,
    "ease_in_back": ease_in_back,
}
