"""Auto-generated Enforcer from academic paper: Procedural Pixel Art via Wave Function Collapse

Generated by SESSION-186 Auto-Enforcer Synthesizer.
Source: https://example.com/mock/wfc-pixel-art
DO NOT EDIT MANUALLY — this file is managed by the distillation engine.
"""
import math
from mathart.quality.gates.enforcer_registry import (
    EnforcerBase,
    EnforcerResult,
    EnforcerSeverity,
    EnforcerViolation,
    register_enforcer,
)

@register_enforcer
class ProceduralPixelArtViaWaveEnforcer(EnforcerBase):
    @property
    def name(self) -> str:
        return "ProceduralPixelArtViaWaveEnforcer"

    @property
    def source_docs(self) -> list[str]:
        return [
            "Procedural Pixel Art via Wave Function Collapse",
            "https://example.com/wfc_paper"
        ]

    def validate(self, params: dict) -> EnforcerResult:
        violations = []

        # Validate 'tile_size' parameter
        tile_size = params.get("tile_size")
        if tile_size is None:
            violations.append(
                EnforcerViolation(
                    message="Missing 'tile_size' parameter.",
                    severity=EnforcerSeverity.ERROR
                )
            )
        else:
            min_tile_size, max_tile_size = 8, 64
            if not isinstance(tile_size, (int, float)):
                violations.append(
                    EnforcerViolation(
                        message="'tile_size' should be a number.",
                        severity=EnforcerSeverity.ERROR
                    )
                )
            else:
                if tile_size < min_tile_size:
                    params["tile_size"] = min_tile_size
                elif tile_size > max_tile_size:
                    params["tile_size"] = max_tile_size

        # Validate 'overlap' parameter
        overlap = params.get("overlap")
        if overlap is None:
            violations.append(
                EnforcerViolation(
                    message="Missing 'overlap' parameter.",
                    severity=EnforcerSeverity.ERROR
                )
            )
        else:
            min_overlap, max_overlap = 1, 5
            if not isinstance(overlap, (int, float)):
                violations.append(
                    EnforcerViolation(
                        message="'overlap' should be a number.",
                        severity=EnforcerSeverity.ERROR
                    )
                )
            else:
                if overlap < min_overlap:
                    params["overlap"] = min_overlap
                elif overlap > max_overlap:
                    params["overlap"] = max_overlap

        return EnforcerResult(params=params, violations=violations)
