"""Auto-generated Enforcer from academic paper: Spring-Damper Procedural Animation for 2D Characters

Generated by SESSION-186 Auto-Enforcer Synthesizer.
Source: https://example.com/mock/spring-damper-anim
DO NOT EDIT MANUALLY — this file is managed by the distillation engine.
"""
import math
from mathart.quality.gates.enforcer_registry import (
    EnforcerBase,
    EnforcerResult,
    EnforcerSeverity,
    EnforcerViolation,
    register_enforcer,
)

@register_enforcer
class SpringdamperProceduralAnimationFor2dEnforcer(EnforcerBase):
    @property
    def name(self) -> str:
        return "SpringdamperProceduralAnimationFor2dEnforcer"

    @property
    def source_docs(self) -> list[str]:
        return [
            "Spring-Damper Procedural Animation for 2D Characters",
            "https://example.com/spring-damper-2d-paper"
        ]

    def validate(self, params: dict) -> EnforcerResult:
        violations = []
        corrected_params = params.copy()

        # Validate 'stiffness' parameter
        if 'stiffness' in params:
            value = params['stiffness']
            min_val, max_val = 10.0, 1000.0
            if value < min_val:
                corrected_params['stiffness'] = min_val
                violations.append(EnforcerViolation(
                    parameter='stiffness',
                    message=f"Stiffness below minimum ({min_val}), auto-corrected.",
                    severity=EnforcerSeverity.WARNING
                ))
            elif value > max_val:
                corrected_params['stiffness'] = max_val
                violations.append(EnforcerViolation(
                    parameter='stiffness',
                    message=f"Stiffness above maximum ({max_val}), auto-corrected.",
                    severity=EnforcerSeverity.WARNING
                ))
        else:
            violations.append(EnforcerViolation(
                parameter='stiffness',
                message="Missing 'stiffness' parameter.",
                severity=EnforcerSeverity.ERROR
            ))

        # Validate 'damping' parameter
        if 'damping' in params:
            value = params['damping']
            min_val, max_val = 0.1, 10.0
            if value < min_val:
                corrected_params['damping'] = min_val
                violations.append(EnforcerViolation(
                    parameter='damping',
                    message=f"Damping below minimum ({min_val}), auto-corrected.",
                    severity=EnforcerSeverity.WARNING
                ))
            elif value > max_val:
                corrected_params['damping'] = max_val
                violations.append(EnforcerViolation(
                    parameter='damping',
                    message=f"Damping above maximum ({max_val}), auto-corrected.",
                    severity=EnforcerSeverity.WARNING
                ))
        else:
            violations.append(EnforcerViolation(
                parameter='damping',
                message="Missing 'damping' parameter.",
                severity=EnforcerSeverity.ERROR
            ))

        # Validate 'mass' parameter
        if 'mass' in params:
            value = params['mass']
            min_val, max_val = 0.01, 1.0
            if value < min_val:
                corrected_params['mass'] = min_val
                violations.append(EnforcerViolation(
                    parameter='mass',
                    message=f"Mass below minimum ({min_val}), auto-corrected.",
                    severity=EnforcerSeverity.WARNING
                ))
            elif value > max_val:
                corrected_params['mass'] = max_val
                violations.append(EnforcerViolation(
                    parameter='mass',
                    message=f"Mass above maximum ({max_val}), auto-corrected.",
                    severity=EnforcerSeverity.WARNING
                ))
        else:
            violations.append(EnforcerViolation(
                parameter='mass',
                message="Missing 'mass' parameter.",
                severity=EnforcerSeverity.ERROR
            ))

        return EnforcerResult(params=corrected_params, violations=violations)
